### ISSUE TITLE
[NEW ICON] Selenium

### ISSUE THREAD

**Issue by Emad-Eldin-G** [tandpfun/skill-icons#100]
### Skill Name

Selenium 

### Why?

Widely used in Web Testing and Automation, and would be a great addition (Especially for Web-Developers)

### Reference Image

![983927](https://user-images.githubusercontent.com/93835389/172086669-2a72382f-7ff7-46b6-8c66-dce9fba4eddc.png)

**Comment by tandpfun** [comment]
Added in f100fddcf1ce9893e3c38be204a0adcfccfd18aa
