### ISSUE TITLE
[NEW ICON] Stream-Lit and other python data analysis libs

### ISSUE THREAD

**Issue by NaChIkEt-pen** [tandpfun/skill-icons#1004]
### Skill Name

Stream-Lit and other python data analysis libs

### Why?

They are popular in python data science and analysis

### Reference Image

https://www.google.com/imgres?q=streamlit&imgurl=https%3A%2F%2Fimages.datacamp.com%2Fimage%2Fupload%2Fv1640050215%2Fimage27_frqkzv.png&imgrefurl=https%3A%2F%2Fwww.datacamp.com%2Ftutorial%2Fstreamlit&docid=mjAOpFZJ9Ls3ZM&tbnid=06SN0Yk9yzwddM&vet=12ahUKEwjcr4vjkeKGAxV6e2wGHTQDCo0QM3oECBUQAA..i&w=1999&h=1170&hcb=2&ved=2ahUKEwjcr4vjkeKGAxV6e2wGHTQDCo0QM3oECBUQAA

**Comment by LelouchFR** [comment]
@NaChIkEt-pen Streamlit icon has been added on the newest version of the project ([here](https://github.com/lelouchfr/skill-icons)) and tone of other icons too, since the maintainer did not show up in months.
