### ISSUE TITLE
[NEW ICON] CMake

### ISSUE THREAD

**Issue by mjovanc** [tandpfun/skill-icons#102]
### Skill Name

CMake

### Why?

It's a very popular build tool for C/C++ to generate makefiles.

### Reference Image

![CMake-Logo-and-Text-e1540917038464-1200x389](https://user-images.githubusercontent.com/33717111/172703462-a2cda872-d5fe-4346-91db-00e67d351701.png)

**Comment by tandpfun** [comment]
Added in f100fddcf1ce9893e3c38be204a0adcfccfd18aa
