### ISSUE TITLE
[NEW ICON] GCC

### ISSUE THREAD

**Issue by mjovanc** [tandpfun/skill-icons#104]
### Skill Name

GCC

### Why?

One of the most popular compilers of C/C++.

### Reference Image

![GNU_Compiler_Collection_logo svg](https://user-images.githubusercontent.com/33717111/172704777-11f3b7a8-8aa9-4784-b757-d068d1c8741e.png)

**Comment by tandpfun** [comment]
Not exactly a skill, there's already a CPP logo.
