### ISSUE TITLE
[NEW ICON] RxJava

### ISSUE THREAD

**Issue by mjovanc** [tandpfun/skill-icons#106]
### Skill Name

RxJava

### Why?

Popular asynchronous framework for Java.

### Reference Image

![download](https://user-images.githubusercontent.com/33717111/172707024-b25a8205-a1b8-432c-b581-9d3931b359b0.png)

**Comment by tandpfun** [comment]
Added in f100fddcf1ce9893e3c38be204a0adcfccfd18aa
