### ISSUE TITLE
[NEW ICON] SQL

### ISSUE THREAD

**Issue by mjovanc** [tandpfun/skill-icons#107]
### Skill Name

SQL

### Why?

SQL is a language which is used in most relational databases.

### Reference Image

Just took a picture that I found on Google. Could be different one. 

![Screenshot 2022-06-08 at 22 07 18](https://user-images.githubusercontent.com/33717111/172707380-ecda970a-60d1-4445-b2f2-6c1e6b8a4e46.png)

**Comment by ThatOneCalculator** [comment]
SQL is a standard. There are already skill labels for PostgreSQL, MySQL/MariaDB, and SQLite.

**Comment by tandpfun** [comment]
I do wish there was a generalized icon, as SQL is a "language" to learn

**Comment by ThatOneCalculator** [comment]
SQL has never had and probably never will have an official logo, sadly

**Comment by grambharos** [comment]
What about OracleDB
Can we add that icon ?

**Comment by tandpfun** [comment]
> What about OracleDB Can we add that icon ?

Please create a separate issue for it!

**Comment by tandpfun** [comment]
Closing because missing official logo

**Comment by MikalaiLappo** [comment]
I'd like to display my top languages from Codewars, and its api has all RDBMSs generalized into one SQL category

It would be cool if there was some general SQL icon

**Comment by ThatOneCalculator** [comment]
The thing is, there isn't one that exists...
