### ISSUE TITLE
[NEW ICON] Groovy

### ISSUE THREAD

**Issue by mjovanc** [tandpfun/skill-icons#108]
### Skill Name

Groovy

### Why?

Very popular language based on Java used for tools such as Gradle.

### Reference Image

![images](https://user-images.githubusercontent.com/33717111/172707880-cbf07ebc-2ceb-494c-93f7-3a97c7cf1a3a.jpeg)

**Comment by ThatOneCalculator** [comment]
Groovy is mostly deprecated in favor of Kotlin.
