### ISSUE TITLE
[NEW ICON] Puppeteer

### ISSUE THREAD

**Issue by Muh-Hamza-99** [tandpfun/skill-icons#115]
### Skill Name

Puppeteer

### Why?

An awesome browser automation library for javascript developers. From web scraping and headless Chrome automation, to running tests for your applications, it truely is just AWESOME!

### Reference Image

![Puppeteer](https://user-images.githubusercontent.com/94744748/174678531-643029b3-eb92-4530-afe8-4fba5c7038b9.svg)

**Comment by tandpfun** [comment]
I think this is a little too specific to count as its own skill.

**Comment by Muh-Hamza-99** [comment]
> I think this is a little too specific to count as its own skill.

Isn't that also the case for Discord.js? Discord.js, which you seem to be thinking about from what I have seen in the replies under the Discord.js suggestion, has a mere 3.5k downloads compared to Puppeteer's 3.5m downloads. I feel Discord.js is a more specific skill than Puppeteer; Discord.js is used for discord bots primarily, while Puppeteer can be used to make scrapers, general-purpose bots and testing applications.

However, the decision is up to you ☺.

**Comment by tandpfun** [comment]
Discord.js has 173 million downloads lol, but I do see what you mean. I think discord bots/discord.js is more of a skill and a lot more complicated than puppeteer which is more of scraping/loading websites. I do think discord.js could be encompassed with the bots or discord icon though. But like in industry or just on a profile, knowing discord.js is a lot more relevant than knowing puppeteer in my opinion.

**Comment by Muh-Hamza-99** [comment]
> Discord.js has 173 million downloads lol, but I do see what you mean. I think discord bots/discord.js is more of a skill and a lot more complicated than puppeteer which is more of scraping/loading websites. I do think discord.js could be encompassed with the bots or discord icon though. But like in industry or just on a profile, knowing discord.js is a lot more relevant than knowing puppeteer in my opinion.

Hmm....yeh I do get your point. Okay thanks man!
