### ISSUE TITLE
[NEW ICON] Neo4J

### ISSUE THREAD

**Issue by ghost** [tandpfun/skill-icons#1172]
### Skill Name

Neo4J

### Why?

It is a graph-based NoSQL database and is used for native graph storage, data science, ML, analytics, and visualization with enterprise-grade security controls to scale your transactional and analytical workloads, without constraints.

### Reference Image

![Neo4J](https://github.com/user-attachments/assets/20d80b25-d633-4d6b-97b8-ffff9a8f3a7f)

**Comment by syvixor** [comment]
I created a new project since this project is no longer updating & the author left it, neo4j is available [skills-icons](https://github.com/ixrzr/skills-icons)

https://skills-icons.vercel.app/api/icons?i=neo4j

![](https://skills-icons.vercel.app/api/icons?i=neo4j)

**Comment by ghost** [comment]
Thank you!
