### ISSUE TITLE
[NEW ICON] Framer

### ISSUE THREAD

**Issue by Akarshjha03** [tandpfun/skill-icons#1174]
### Skill Name

Framer

### Why?

Framer is a powerful tool for designing interactive prototypes and UI components, and having a dedicated icon for it would greatly enhance its visibility and recognition.

Usage: This icon will help designers and developers quickly identify Framer-related components in their projects and documentation.

Community Impact: Adding this icon will improve the repository's coverage of design tools and make it more valuable for users working with Framer.

### Reference Image

![framerlogo](https://github.com/user-attachments/assets/6ece63d4-ffef-4f52-af56-3cf67e6a2149)

**Comment by syvixor** [comment]
I created a new project since this project is no longer updating & the author left it, framer is available [skills-icons](https://github.com/ixrzr/skills-icons)

https://skills-icons.vercel.app/api/icons?i=framer

![](https://skills-icons.vercel.app/api/icons?i=framer)

**Comment by Akarshjha03** [comment]
Is it feasible to implement this feature directly in the README?

**Comment by syvixor** [comment]
> Is it feasible to implement this feature directly in the README?

yes it's doing the same job as skill icons, like i said 
> I created a new project since this project is no longer updating & the author left it
