### ISSUE TITLE
[NEW ICON] Linden Scripting Language (LSL)

### ISSUE THREAD

**Issue by neuromodgames** [tandpfun/skill-icons#118]
### Skill Name

Linden Scripting Language

### Why?

It's the standard coding language for Second Life, which has a wealth of content creators even to this day.

### Reference Image

![Second_Life_Logo](https://user-images.githubusercontent.com/88777150/175248461-21a3c6ec-8ba8-4321-b37f-9dd13646ad82.svg)
![49923608423_dc8669ff56_o](https://user-images.githubusercontent.com/88777150/175248479-e7b17092-9a79-41c5-b381-2a791c4ab62e.png)

**Comment by tandpfun** [comment]
A little bit too specific of a language to be an icon.
