### ISSUE TITLE
[BUG REPORT] PICTURE&SOURCE tag

### ISSUE THREAD

**Issue by unSerori** [tandpfun/skill-icons#1195]
### The bug

GitHub profile README.md only shows the first icon when retrieving multiple icons.
Note that if you simply use the API in a browser or VS Code viewer, all images are displayed correctly.

But this may be a problem with GitHub itself

### Steps to reproduce

```html
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://skillicons.dev/icons?theme=dark&perline=9&i=java,kotlin,nodejs,figma" />
  <source media="(prefers-color-scheme: light)" srcset="https://skillicons.dev/icons?theme=light&perline=9&i=java,kotlin,nodejs,figma" />
  <img width= alt="Icons for favorite tools, lang and mySkills." src="https://skillicons.dev/icons?theme=light&perline=9&i=java,kotlin,nodejs,figma" />
</picture>
```

### Any extra info

I have created a repository for explanatory purposes.
[https://github.com/unSerori/skill-icons-bug-sample](https://github.com/unSerori/skill-icons-bug-sample)

**Comment by AleksaMCode** [comment]
This isn't a bug. Markdown itself doesn't support `<picture>` element or advanced HTML features (e.q. `<source>`). What you are trying to do here just isn't possible.

**Comment by unSerori** [comment]
Thank you！
