### ISSUE TITLE
[NEW ICONS] [ALREADY MADE] V, LaTeX, .NET, Vala

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#12]
### Skill Name

TeX, Vala, .NET, V

### Why?

- LaTeX: most popular document language, if markdown is here then TeX/LaTeX should be for sure
- .NET: very popular programing language
- V: popular programming language
- Vala: popular programming language

### Completed icons

![V-Light](https://user-images.githubusercontent.com/44733677/157992697-1374513a-3168-4d6a-992e-df08fa4152cb.svg) ![V-Dark](https://user-images.githubusercontent.com/44733677/157992613-e251d196-c83d-4872-8dc7-cd95e7fa2a39.svg)

![LaTeX-Light](https://user-images.githubusercontent.com/44733677/157993600-9905507a-e069-4acb-998a-cfbdaafe099a.svg) ![LaTeX-Dark](https://user-images.githubusercontent.com/44733677/157993601-754f00ce-e07d-415b-a6bb-6eb0f17af508.svg)

![DotNet](https://user-images.githubusercontent.com/44733677/157992796-806ec850-b3a2-4ad1-8af6-7ce5cd4376e0.svg)

![Vala](https://user-images.githubusercontent.com/44733677/157993854-5b0634bd-0f8d-4d12-adea-472b9dcf7fdb.svg)

**Comment by tandpfun** [comment]
Added in 690c3f2. Thank you!
