### ISSUE TITLE
NEW ICON: Postman

### ISSUE THREAD

**Issue by sourish215** [tandpfun/skill-icons#120]
### Skill Name

Postman

### Why?

Postman is a popular application used by developers to test APIs. Please consider adding the postman icon to your awesome collection. Thank you very much.

**Comment by Codeize** [comment]
Duplicate of #114

**Comment by skepfusky** [comment]
Hey @sourish215, someone already requested Postman from #114, marking this as duplicate.

**Comment by sourish215** [comment]
Okay @kuroji-fusky !
