### ISSUE TITLE
[NEW ICON] Sublime Text

### ISSUE THREAD

**Issue by leolin49** [tandpfun/skill-icons#123]
### Skill Name

Sublime Text

### Why?

Sublime Text is a shareware cross-platform source code editor. It natively supports many programming languages and markup languages. Users can expand its functionality with plugins.

### Reference Image

![SublimeText-Dark](https://user-images.githubusercontent.com/58925286/177300895-8897087e-9a1e-4439-ab69-664bb48ad604.svg)
![SublimeText-Light](https://user-images.githubusercontent.com/58925286/177301296-9318b28b-ab13-4968-b597-38537f0458c5.svg)

**Comment by ItsAleph** [comment]
I dont personally agree with this being "low priority" :(

**Comment by tandpfun** [comment]
Added in e67133b!

**Comment by elenakrittik** [comment]
Thanks! Also, sorry for being a little rude in the previous comment, feels like i was a completely different person back then haha
