### ISSUE TITLE
[NEW ICON] RabbitMQ & Apache Kafka

### ISSUE THREAD

**Issue by Louis3797** [tandpfun/skill-icons#125]
### Skill Name

RabbitMQ, Apache Kafka

### Why?

Both are very popular technologies!

## RabbitMQ
Popular Message Broker

Used by: Reddit, RobinHood, Indeed, CircleCI, Fiverr

## Apache Kafka
Popular alternative for RabbitMQ 

Used by: Spotify, Goldman Sachs, Airbnb, Pinterest, Adidas, Zalando

## RabbitMQ:
![rabbitmq](https://user-images.githubusercontent.com/53270473/177349940-20582421-1330-4c20-90c9-0342147b6eb5.svg)
## Apache Kafka:
![kafka](https://user-images.githubusercontent.com/53270473/177350016-a3d89ecb-22fc-41fd-8b61-a81a01a7f3d1.svg)

**Comment by tandpfun** [comment]
✅ Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
