### ISSUE TITLE
[NEW ICON] Dev.to

### ISSUE THREAD

**Issue by Louis3797** [tandpfun/skill-icons#126]
### Skill Name

Dev.to

### Why?

More social media links
its popular

### Reference Image

![devto](https://user-images.githubusercontent.com/53270473/177352322-91495c19-b3d1-4b31-a04b-b20e31c256ff.svg)

**Comment by tandpfun** [comment]
✅ Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
