### ISSUE TITLE
[NEW ICON] Xcode

### ISSUE THREAD

**Issue by RyouDYFZ** [tandpfun/skill-icons#1268]
### Skill Name

Xcode

### Why?

The IDE of Apple with essential tools for developers who develops on iOS, iPadOS, macOS and more

### Reference Image

![xcode-12-96x96_2x](https://github.com/user-attachments/assets/cf311d23-dbc6-4f76-b644-1d145369408f)

**Comment by rafinhaa** [comment]
+1

**Comment by syvixor** [comment]
I created a new project since this project is no longer updating & the author left it, xcode is available [skills-icons](https://github.com/ixrzr/skills-icons)

https://skills-icons.vercel.app/api/icons?i=xcode

![](https://skills-icons.vercel.app/api/icons?i=xcode)
