### ISSUE TITLE
[NEW ICON] Visual Basic .NET

### ISSUE THREAD

**Issue by skepfusky** [tandpfun/skill-icons#127]
### Skill Name

Visual Basic .NET or VB.NET

### Why?

VB.NET is a language that is based on the .NET framework, mostly cooperated with a GUI designer

### Reference Image

![a](https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/VB.NET_Logo.svg/512px-VB.NET_Logo.svg.png)

**Comment by tandpfun** [comment]
Do you think it counts as a separate skill, or does it fall under .net?

**Comment by skepfusky** [comment]
I guess I would consider it as a separate skill since there are still a handful of people still building VB apps since it's a language that is under the .NET ecosystem
