### ISSUE TITLE
[BUG REPORT] Kotlin logo is outdated: colors changed

### ISSUE THREAD

**Issue by LouisCAD** [tandpfun/skill-icons#128]
### The problem

Hello, the Kotlin logo is outdated: colors changed to red and purple (or just purple). I'll let you find the right image on the web, but feel free to ask any question if needed.

### Any extra info

Here are the two official colors if needed: #7F52FF #E44857 (source: https://youtrack.jetbrains.com/issue/KT-46792/Update-community-graphic-assets-to-the-new-Kotlin-visual-style#focus=Comments-27-6087024.0-0)

**Comment by AstroAnasTariq** [comment]
More official Resources:
https://kotlinlang.org/docs/kotlin-brand-assets.html 

![Kotlin_new_icon](https://user-images.githubusercontent.com/57492251/180583841-7aeaf334-9a24-475a-b8ef-fa94ddf472ab.png)

**Comment by LouisCAD** [comment]
Thanks for addressing @tandpfun!

I noticed the `readme.md` file uses a non dynamic image that currently contains the old Kotlin logo (under the "Themed Icons" heading), so it'd need to be updated as well, or be switched to a dynamic version to avoid future recurrence in case any logo in said image changes.

**Comment by tandpfun** [comment]
It is dynamic, but GitHub caches it. It might resolve itself in a few days. If not I can probably do something to bypass cache.

**Comment by LouisCAD** [comment]
It's weird, out of the 2 times the Kotlin logo is displayed, the second occurrence (the one in the list) is up to date, but the first one that sits next to 3 other logos on a single image, is still on the old logo.
