### ISSUE TITLE
[NEW ICON] JWT

### ISSUE THREAD

**Issue by Mobin-Abbasi** [tandpfun/skill-icons#1298]
### Skill Name

JWT

### Why?

So that we can demonstrate our skills more accurately by displaying these skills.

### Reference Image

![image](https://github.com/user-attachments/assets/463579e6-2615-4d5f-ad42-2a9015571b1c)

**Comment by syvixor** [comment]
I created a new project since this project is no longer updating & the author left it, jwt is available [skills-icons](https://github.com/ixrzr/skills-icons)

https://skills-icons.vercel.app/api/icons?i=jwt

![](https://skills-icons.vercel.app/api/icons?i=jwt)
