### ISSUE TITLE
[NEW ICON] swagger

### ISSUE THREAD

**Issue by Mobin-Abbasi** [tandpfun/skill-icons#1299]
### Skill Name

swagger

### Why?

So that we can demonstrate our skills more accurately by displaying these skills.

### Reference Image

![image](https://github.com/user-attachments/assets/937877cd-c819-4383-86e5-4322a0176d4e)

**Comment by syvixor** [comment]
I created a new project since this project is no longer updating & the author left it, swagger is available [skills-icons](https://github.com/ixrzr/skills-icons)

https://skills-icons.vercel.app/api/icons?i=swagger

![](https://skills-icons.vercel.app/api/icons?i=swagger)
