### ISSUE TITLE
[(sorta) NEW ICON] Re-introduce SVG

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#13]
### Skill Name

SVG

### Why?

The icon was previously broken but should be fine now

### Completed icons

![SVG-Light](https://user-images.githubusercontent.com/44733677/157997554-648cd4c9-09d4-4e07-8572-d1964e273a8a.svg) ![SVG-Dark](https://user-images.githubusercontent.com/44733677/157997562-03398bdd-5ee9-4e94-b1eb-d984d6bb00b5.svg)

**Comment by ThatOneCalculator** [comment]
Update: not fixed on everyone's end, closing for now until truly fixed.

**Comment by tandpfun** [comment]
Added in d32c069
