### ISSUE TITLE
[NEW ICON] Shadcn UI

### ISSUE THREAD

**Issue by IryDev** [tandpfun/skill-icons#1313]
### Why?

A popular beautifully designed components that you can copy and paste into your apps. Made with Tailwind CSS. Open source.

### Reference Image

![139895814](https://github.com/user-attachments/assets/764dbfd8-ff40-4b2d-b315-ab474bfa04dd)
![shadcn-ui-logo-EF735EC0E5-seeklogo com](https://github.com/user-attachments/assets/ad2530cd-16ad-446f-970a-e94aed22712a)

**Comment by syvixor** [comment]
I created a new project since this project is no longer updating & the author left it, shadcnui is available [skills-icons](https://github.com/ixrzr/skills-icons)

https://skills-icons.vercel.app/api/icons?i=shadcnui

![](https://skills-icons.vercel.app/api/icons?i=shadcnui)

**Comment by IryDev** [comment]
Thanks your icons looks great
