### ISSUE TITLE
[NEW ICON] Proxmox, VMware, VirtualBox

### ISSUE THREAD

**Issue by antoninoLorenzo** [tandpfun/skill-icons#1317]
### Skill Name

Proxmox, VMware, VirtualBox

### Why?

While there are icons for Cloud Computing (`aws`, `gcp`, `azure`), virtualization technologies are still relevant for roles in Cybersecurity, IT infrastructure management and DevOps. 

### Reference Image

[Proxmox](https://www.proxmox.com/images/proxmox/proxmox-brandmark-white.svg), [VMware](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Vmware_workstation_16_icon.svg/150px-Vmware_workstation_16_icon.svg.png), VirtualBox [New](https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/VirtualBox_2024.png/150px-VirtualBox_2024.png)/[Old](https://styles.redditmedia.com/t5_2s4us/styles/communityIcon_ji36jpi09n831.png)

> I suggest the old icon for virtualbox

**Comment by Domenez-dev** [comment]
I can add them if owner assign me to it
I can add packet tracer, ubunto server, windows server gns3 and more..
and for cybersecurity I can add tools like nmap, wireshark, zproxy, metasploit...

**Comment by antoninoLorenzo** [comment]
> and for cybersecurity I can add tools like nmap, wireshark, zproxy, metasploit...

Introducing icons like nmap, metasploit, burp could actually be good. 

However I think that the icons can be added only by owners, or at least the note in the README "... we don't accept pull requests for icon submissions. If you would like an icon added, please open an issue." suggests this.

**Comment by syvixor** [comment]
> ### Skill Name
> Proxmox, VMware, VirtualBox
> 
> ### Why?
> While there are icons for Cloud Computing (`aws`, `gcp`, `azure`), virtualization technologies are still relevant for roles in Cybersecurity, IT infrastructure management and DevOps.
> 
> ### Reference Image
> [Proxmox](https://www.proxmox.com/images/proxmox/proxmox-brandmark-white.svg), [VMware](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Vmware_workstation_16_icon.svg/150px-Vmware_workstation_16_icon.svg.png), VirtualBox [New](https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/VirtualBox_2024.png/150px-VirtualBox_2024.png)/[Old](https://styles.redditmedia.com/t5_2s4us/styles/communityIcon_ji36jpi09n831.png)
> 
> > I suggest the old icon for virtualbox

I created a new project since this project is no longer updating & the author left it, proxmox, vmware & virtualbox are available [skills-icons](https://github.com/ixrzr/skills-icons)

https://skills-icons.vercel.app/api/icons?i=proxmox,vmware,virtualbox

![](https://skills-icons.vercel.app/api/icons?i=proxmox,vmware,virtualbox)
