### ISSUE TITLE
[NEW ICON] Gmail

### ISSUE THREAD

**Issue by thenithinbalaji** [tandpfun/skill-icons#134]
### Skill Name

Gmail

### Why?

For people who give their contact mail ids in the readme.

**Comment by skepfusky** [comment]
@thenithinbalaji I apologize that this was already suggested at issue #92 and was closed for not being skill worthy. Reference: https://github.com/tandpfun/skill-icons/issues/92#issuecomment-1155854173

**Comment by thenithinbalaji** [comment]
@skepfusky I thought we could add it because the repo already has Twitter, StackOverflow, Discord

**Comment by thenithinbalaji** [comment]
> @skepfusky I thought we could add it because the repo already has Twitter, StackOverflow, Discord
Oh wait, are those skills?

**Comment by skepfusky** [comment]
Oh, but tandpfun closed it apparently, I dunno lol

**Comment by thenithinbalaji** [comment]
This explanation https://github.com/tandpfun/skill-icons/issues/53#issuecomment-1073038375 applies to Gmail as well 
@tandpfun @skepfusky 🤔

**Comment by skepfusky** [comment]
Who knows, I'm just a contributor 🤷

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!
