### ISSUE TITLE
[NEW ICON] Wayland

### ISSUE THREAD

**Issue by rv178** [tandpfun/skill-icons#136]
### Skill Name

Wayland

### Why?

> Wayland is a communication protocol that specifies the communication between a display server and its clients, as well as a C library implementation of that protocol.A display server using the Wayland protocol is called a Wayland compositor, because it additionally performs the task of a compositing window manager

It would be a good addition since people who are developing wayland clients/compositors will have an icon they can use!

### Reference Image

https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Wayland_Logo.svg/200px-Wayland_Logo.svg.png

**Comment by tandpfun** [comment]
I think this icon is too specific of a skill.
