### ISSUE TITLE
[NEW ICON] JetBrains ideas besides Intellij idea

### ISSUE THREAD

**Issue by razlevio** [tandpfun/skill-icons#139]
### Skill Name

PyCharm, DataGrip, WebStorm

### Why?

Because those are widely used ide's

**Comment by skepfusky** [comment]
@razlevio Hate to break it to ya, but someone suggested PyCharm (#79) and I suggested WebStorm and PhpStorm (#80) on but IDEs aren't considered skills as referenced on https://github.com/tandpfun/skill-icons/issues/79#issuecomment-1133791600
