### ISSUE TITLE
[NEW ICON] NestJS

### ISSUE THREAD

**Issue by d0ugui** [tandpfun/skill-icons#14]
### Skill Name

NestJS

### Why?

**Skill Name**
NestJS

**Why?**
NestJS is a popular back-end framework

**Reference Images (optional)**
[Example](https://icon-icons.com/pt/icone/arquivo-tipo-nestjs/130355).

**Comment by ThatOneCalculator** [comment]
Proposal:
![NestJS-Light](https://user-images.githubusercontent.com/44733677/158000649-fc630edf-a9a7-4027-8d33-ca18c77bfa54.svg) ![NestJS-Dark](https://user-images.githubusercontent.com/44733677/158000650-f3f68b18-f569-4064-a2e9-113d37db1064.svg)

**Comment by warengonzaga** [comment]
This is perfect!

**Comment by tandpfun** [comment]
Added in 28fb8ab
