### ISSUE TITLE
[NEW ICON] Sequelize.js

### ISSUE THREAD

**Issue by Muh-Hamza-99** [tandpfun/skill-icons#141]
### Skill Name

Sequelize

### Why?

Most popular ORM out there for Javascript developers when using relational databases.

### Reference Image

![Sequelize](https://user-images.githubusercontent.com/94744748/179084180-f782438f-f5ef-41f7-829c-8b1abc092891.svg)

**Comment by tandpfun** [comment]
✅ Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
