### ISSUE TITLE
[NEW ICON] Flink

### ISSUE THREAD

**Issue by hoey94** [tandpfun/skill-icons#142]
### Skill Name

flink

### Why?

Want to add Flink

### Reference Image

https://camo.githubusercontent.com/a15ce3759602e005c345a3b0c8e6adf0f6a998d0404854eb77a21840abbaee38/68747470733a2f2f666c696e6b2e6170616368652e6f72672f696d672f6c6f676f2f706e672f3130302f666c696e6b5f737175697272656c5f3130305f636f6c6f722e706e67

**Comment by skepfusky** [comment]
@hoey94  ...could you at least tell exactly _why_ you're adding it? You've also seem to forgot to change the issue name of the icon you're suggesting, same applies for #143.
