### ISSUE TITLE
[NEW ICON] Terraform

### ISSUE THREAD

**Issue by Muh-Hamza-99** [tandpfun/skill-icons#147]
### Skill Name

Terraform

### Why?

A high-in-demand DevOps skill, commonly used for automation of cloud infrastructure, but also has other applications, such as Kubernetes.

### Reference Image

![Terraform](https://user-images.githubusercontent.com/94744748/179433273-723df25d-8bc8-4397-b626-179fb3253daa.svg)

**Comment by AnoyiX** [comment]
[![](https://icons.anoyi.com/?theme=light&icons=terraform)](https://anoyi.com/dev-icons) [![](https://icons.anoyi.com/?icons=terraform)](https://anoyi.com/dev-icons)

You can try [https://github.com/AnoyiX/dev-icons](https://github.com/AnoyiX/dev-icons)

**Comment by mjovanc** [comment]
Why is this low priority? This is very used tool today.

**Comment by elmazzun** [comment]
I second @mjovanc's statement, Terraform is worth its own icon.

**Comment by harrisonj94** [comment]
100% need this

**Comment by elmazzun** [comment]
Given the current situation, maybe OpenTofu logo would also be good?

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!
