### ISSUE TITLE
[NEW ICON] Delphi

### ISSUE THREAD

**Issue by FelixEcker** [tandpfun/skill-icons#148]
### Skill Name

Delphi

### Why?

Delphi is a derivative of Object Pascal and still finds use in the Software industry for GUI applications.

### Reference Image

![Embarcadero_Delphi_10 4_Sydney_Product_Logo_and_Icon_004](https://user-images.githubusercontent.com/31585250/179732860-35132afb-4ff8-4d05-8fb4-c9f7ea2eaf5d.png)

**Comment by tandpfun** [comment]
I don't think this is a popular/modern skill

**Comment by FelixEcker** [comment]
fair enough
