### ISSUE TITLE
[NEW ICON] Oracle and SQL Server

### ISSUE THREAD

**Issue by yildizmy** [tandpfun/skill-icons#149]
### Skill Name

Oracle, SQL Server

### Why?

Oracle and SQL Server are commonly used relational database systems and lots of developer would use these icon with the icon set.

### Reference Image

![d22348bd363fbf1ad4ab10e2b660b6ab](https://user-images.githubusercontent.com/11348681/180082081-970af9bb-1760-4c90-97d2-c1d82ff9545c.png)

![microsoft-sql-server-logo-01-1024x1024](https://user-images.githubusercontent.com/11348681/180082247-37096861-734b-4035-b45e-7fd40747cc0d.png)

**Comment by tandpfun** [comment]
Oracle isn't really a skill, and I don't think sql server is exactly one either

**Comment by yildizmy** [comment]
What about PostgreSQL? Then why don't you just use SQL instead of PostgreSQL?

**Comment by eduarddejong** [comment]
SQL Server is absolutely a separate skill. it has a lot of specific technology.
Understanding databases and SQL is one thing, but having deeper knowledge of SQL Server as a specific thing is really a different thing. This also includes a lot of management tasks, als well as the T-SQL language variant, which has many specific things as well.
