### ISSUE TITLE
[NEW ICON] Moodle

### ISSUE THREAD

**Issue by leonardoanthony** [tandpfun/skill-icons#150]
### Skill Name

Moodle

### Why?

The most popular course management system (CMS)

### Reference Image

https://www.ifmg.edu.br/ourobranco/noticias/curso-do-moodle-esta-disponivel-para-os-alunos-do-campus-ouro-branco

**Comment by tandpfun** [comment]
I don't think moodle is a programming-related skill

**Comment by leonardoanthony** [comment]
but wordpress...
