### ISSUE TITLE
[NEW ICON] HackerRank

### ISSUE THREAD

**Issue by AstroAnasTariq** [tandpfun/skill-icons#155]
### Skill Name

HackerRank

### Why?

Because it's a world's-Leading website to practice solving problems, it's important for software engineers to have a link to their HackerRank profile in GitHub readme.

### Reference Image

![d3d80100-5380-11eb-8996-8dd7f746dcc3](https://user-images.githubusercontent.com/57492251/180588683-bba75bce-d91f-44c4-8e50-4dcb16ab6ab3.png)

**Comment by tandpfun** [comment]
This isn't exactly a skill either

**Comment by yildizmy** [comment]
Yeah, but Instagram is a skill as you created icon for it and must have more relation regarding to software development than Hackerrank. It is clearly seen that you have some troubles for specifying skills.
