### ISSUE TITLE
[NEW ICONS] [ALREADY MADE 🥳] BSD, Plan9

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#16]
### Skill Name

BSD, Plan9

### Why?

BSD and Plan9 is are popular Unix-like, non-Linux OSes used for development and servers.

### Completed icons

I actually made the Glenda (Plan9) svg myself, because the official Plan9 logo is a .jpg
I'm unsure if the SVG needs to me fixed in any way.

![BSD-Light](https://user-images.githubusercontent.com/44733677/158000543-7632d0dc-b7eb-4288-9751-818333ac0240.svg) ![BSD-Dark](https://user-images.githubusercontent.com/44733677/158000545-36f55716-55fd-47f1-9f91-3d4fdb76442a.svg)

![Plan9-Light](https://user-images.githubusercontent.com/44733677/158000445-e5ced0d3-7b28-48cc-8965-e96e1a187041.svg) ![Plan9-Dark](https://user-images.githubusercontent.com/44733677/158000441-635e05ec-3447-4bfb-b8cc-8fb98622c81b.svg)

**Comment by tandpfun** [comment]
Added in 28fb8ab, thank you!
