### ISSUE TITLE
[NEW ICON] Three.js

### ISSUE THREAD

**Issue by SauravJalui** [tandpfun/skill-icons#168]
### Skill Name

Three.js

### Why?

It's a JavaScript 3D library to make 3D content for the web

### Reference Image

![Three js_Icon](https://user-images.githubusercontent.com/18356048/183001953-cfcd8665-096b-4a5f-bcba-113063b6a087.png)

**Comment by tandpfun** [comment]
✅ Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
