### ISSUE TITLE
[NEW ICON] [ALREADY MADE 🥳] Rulex

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#17]
### Skill Name

Rulex

### Why?

It's an alternative for ReGeX that's being adopted quickly

### Completed icons

![Rulex-Light](https://user-images.githubusercontent.com/44733677/158003668-59f4f2b5-e937-44be-90ff-0afadaed327a.svg) ![Rulex-Dark](https://user-images.githubusercontent.com/44733677/158003669-70afc714-8a37-4a4c-8e73-85fdcab8f54e.svg)

**Comment by ThatOneCalculator** [comment]
@Benricheson101 any reason for the thumbs down, anything I should know about that makes this a bad suggestion?

**Comment by Benricheson101** [comment]
From what I can tell, it's just a very small library for Rust. I personally don't see the benefit of having an icon for a library that no one has ever heard of.

**Comment by ThatOneCalculator** [comment]
It's cross-plat (not just rust), talked abt it in DMs with the creator and just gonna wait to see if it gets more widely adopted
