### ISSUE TITLE
[NEW ICON] Windows

### ISSUE THREAD

**Issue by Diptonil** [tandpfun/skill-icons#170]
### Skill Name

Windows

### Why?

It's popular as an OS.

### Reference Image

![microsoft-windows-22](https://user-images.githubusercontent.com/26021114/183726766-d5bcb21d-79db-4ba2-9a17-c063d4ea908c.svg)

**Comment by AnoyiX** [comment]
[![](https://icons.anoyi.com/?icons=windows)](https://anoyi.com/dev-icons)

You can try [https://github.com/AnoyiX/dev-icons](https://github.com/AnoyiX/dev-icons)

**Comment by tandpfun** [comment]
Added in e67133b!
