### ISSUE TITLE
[NEW ICON] Sentry

### ISSUE THREAD

**Issue by Diptonil** [tandpfun/skill-icons#171]
### Skill Name

Sentry

### Why?

It's popular for error detection and logging.

### Reference Image

![sentry-glyph-dark-400x367](https://user-images.githubusercontent.com/26021114/183727235-5cee7199-abab-41b9-bb0c-c31e3fcab662.svg)

**Comment by tandpfun** [comment]
✅ Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
