### ISSUE TITLE
[NEW ICON] ElasticSearch

### ISSUE THREAD

**Issue by Nomango** [tandpfun/skill-icons#173]
### Skill Name

ElasticSearch

### Why?

It's a widely used full-text search and analytics engine.

[Offical Website](https://www.elastic.co/)

### Reference Image

![elastic-logo](https://user-images.githubusercontent.com/22350366/183864124-b9633575-13b7-4fc0-a331-6c3c3a4d5116.svg)

**Comment by AnoyiX** [comment]
[![](https://icons.anoyi.com/?icons=elastic)](https://anoyi.com/dev-icons)

You can try [https://github.com/AnoyiX/dev-icons](https://github.com/AnoyiX/dev-icons)

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!
