### ISSUE TITLE
[NEW ICON] Gulp

### ISSUE THREAD

**Issue by Diptonil** [tandpfun/skill-icons#176]
### Skill Name

Gulp

### Why?

It's a popular JavaScript build tool.

### Reference Image

![gulp-logo-svgrepo-com](https://user-images.githubusercontent.com/26021114/184650180-8718a262-0ced-45ef-88f2-e1585e1cde37.svg)

**Comment by GeorgeKryptonian** [comment]
I like that idea. But I still don't understand why the `Gulp` icon hasn't been added 😞
It's a fairly `popular` tool.

**Comment by tandpfun** [comment]
✅ Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
