### ISSUE TITLE
[NEW ICON] PlanetScale

### ISSUE THREAD

**Issue by marvin-j97** [tandpfun/skill-icons#182]
### Skill Name

PlanetScale

### Why?

It's a distributed SQL database

https://planetscale.com

### Reference Image

![35612527](https://user-images.githubusercontent.com/33938500/184961227-f52b869e-b717-4c3d-9b69-038313dac585.png)

**Comment by tandpfun** [comment]
Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
