### ISSUE TITLE
[NEW ICON] Canva

### ISSUE THREAD

**Issue by fluentmoheshwar** [tandpfun/skill-icons#184]
### Skill Name

Canva

### Why?

It's an popular design tool.

### Reference Image

![canva-seeklogo com](https://user-images.githubusercontent.com/65463913/185556673-aecb792a-0225-494d-a0ad-037595e0f9ac.svg)

**Comment by josemateuss** [comment]
@fluentmoheshwar canva icon has been merged here https://github.com/LelouchFR/skill-icons/pull/75
