### ISSUE TITLE
[NEW ICON] IPFS

### ISSUE THREAD

**Issue by lertsoft** [tandpfun/skill-icons#187]
### Skill Name

IPFS

### Why?

It's a popular decentralize storage protocol

### Reference Image

![Ipfs-logo](https://user-images.githubusercontent.com/28693094/186185979-f779237f-f202-4be3-9a02-f4d00bac05f8.png)

**Comment by tandpfun** [comment]
Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
