### ISSUE TITLE
[NEW ICON] Skill Name

### ISSUE THREAD

**Issue by Afhamcanva** [tandpfun/skill-icons#188]
### Skill Name

CANVA

### Why?

WHY GIT HUB REMOVED CANVA FOR STUDENTS, ITS HIGHLY HELPFULL FOR STUDENTS,
SO BRING IT BACK SOON !!

**Comment by skepfusky** [comment]
Sorry but this is a duplicate issue; **Canva** was already requested on issue #184

**Comment by skepfusky** [comment]
Btw you don't have to open an issue with excessive caps and issue title unmodified. Be sure to check for any open issues before considering requesting an icon.
