### ISSUE TITLE
[NEW ICON] AdonisJs

### ISSUE THREAD

**Issue by johngerome** [tandpfun/skill-icons#189]
### Skill Name

AdonisJs

### Why?

It's a popular web framework for Node.js with 12.9k ⭐

https://adonisjs.com/

### Reference Image

![image](https://user-images.githubusercontent.com/2002000/186444398-f3cd0e45-4dc3-42c8-9668-d0493564ec87.png)

**Comment by tandpfun** [comment]
Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
