### ISSUE TITLE
[NEW ICON] Scikit Learn

### ISSUE THREAD

**Issue by Muh-Hamza-99** [tandpfun/skill-icons#191]
### Skill Name

Scikit Learn

### Why?

It's the most popular machine learning library for Python. It's beginner-friendly and abstracts a lot of the complexities of machine learning.

### Reference Image

![ScikitLearn](https://user-images.githubusercontent.com/94744748/186983980-9f96e268-727a-455d-9453-e3a84df55420.svg)

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!
