### ISSUE TITLE
[NEW ICON] Babel

### ISSUE THREAD

**Issue by nekiro** [tandpfun/skill-icons#194]
### Skill Name

babel

### Why?

It's very popular transpiler

### Reference Image

![babel-svgrepo-com](https://user-images.githubusercontent.com/14142246/187092966-89c3b316-2917-4db1-963f-9271540614d1.svg)

**Comment by coren-frankel** [comment]
Seconded! But here's a better reference image:

<img src="https://raw.githubusercontent.com/kirukudenis/readme_icons/master/language_and_tools/square/babel/babel.svg">

**Comment by tandpfun** [comment]
Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
