### ISSUE TITLE
[NEW ICON] blockchain

### ISSUE THREAD

**Issue by Oxicode** [tandpfun/skill-icons#2]
**Skill Name**
Blockchain

**Why?**
It's popular for web development

**Reference Images (optional)**
[Example.](https://www.shutterstock.com/es/image-vector/blockchain-icon-vector-block-chain-cryptocurrency-1216673260)

**Comment by ThatOneCalculator** [comment]
"Blockchain" has no unified logo, and would probably be better fit by Solidity, as seen in #5.
