### ISSUE TITLE
[NEW ICONS] [COMPLETED 🥳] Nim, Laravel, AutoCAD, Blender, Unreal Engine, HaxeFlixel, ActivityPub, GameMaker Studio, AiScript, EMACS

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#20]
### Skill Names

- Nim
- Laravel
- AutoCAD
- Blender
- Unreal Engine (`ue`)
- HaxeFlixel
- ActivityPub
- GameMaker Studio (`gamemaker`)
- AiScript
- EMACS

### Why?

- Nim: It's a very popular programming language 
- Laravel: Most popular PHP framework (basically the React of PHP)
- AutoCAD: most popular CAD (Computer assisted design) software, if the Adobe suite is included, AutoCAD makes sense too. 
- Blender: Same as AutoCAD but for 3D work, Blender also incorporates a lot of coding 
- Unreal Engine: very popular game engine, fits in with Unity and Godot
- HaxeFlixel: most popular Haxe graphics library, very very widely used in the FNF community
- ActivityPub: Defacto standard for federated, decentralized communication, powers the Fediverse and is a very useful and powerful programming skill
- GameMaker Studio: very popular pickup-and-play game engine and scripting language.
- AiScript: built in programming language of Misskey, and also acts as a standalone scripting language, more popular in Japan than anywhere else as it was developed specifically for Japanese programmers.
- EMACS: very popular coding environment and programming language

### Reference Image

I'll probably make an icons in the morning, this issue is mostly a reminder to myself.  

https://github.com/nim-lang/assets/tree/master/Art

https://laravel.com/img/logomark.min.svg

https://upload.wikimedia.org/wikipedia/commons/0/08/AutoCad_logo.svg

https://upload.wikimedia.org/wikipedia/commons/3/3c/Logo_Blender.svg

https://upload.wikimedia.org/wikipedia/commons/d/da/Unreal_Engine_Logo.svg

https://haxeflixel.com/images/haxeflixel.svg

https://www.vectorlogo.zone/logos/w3_activitypub/w3_activitypub-icon.svg

https://upload.wikimedia.org/wikipedia/en/7/7a/GameMaker_Studio_2.svg

https://github.com/syuilo/aiscript/raw/master/aiscript.svg

https://upload.wikimedia.org/wikipedia/commons/0/08/EmacsIcon.svg

**Comment by ThatOneCalculator** [comment]
### Nim
![Nim-Light](https://user-images.githubusercontent.com/44733677/158035289-ff27d16c-92e4-4cfc-9f69-dcf36b2fc02b.svg) ![Nim-Dark](https://user-images.githubusercontent.com/44733677/158035290-55113520-8ce5-4a2a-86a6-a36d3b00725c.svg)

### Laravel
![Laravel-Light](https://user-images.githubusercontent.com/44733677/158035287-3d42a0c9-dccd-45bf-aeee-174cbcfb7628.svg) ![Laravel-Dark](https://user-images.githubusercontent.com/44733677/158035288-e557b27f-07ad-44ad-93bf-3802191b3c91.svg)

### AutoCAD
![AutoCAD-Light](https://user-images.githubusercontent.com/44733677/158035283-880a7bf7-4869-445a-913a-921a16157735.svg) ![AutoCAD-Dark](https://user-images.githubusercontent.com/44733677/158035285-01800ad0-7f2f-4b26-9cd0-0989efb83822.svg)

### Blender
![Blender-Light](https://user-images.githubusercontent.com/44733677/158035279-a95e999f-a77b-43c9-86c4-8fbe64fccba9.svg) ![Blender-Dark](https://user-images.githubusercontent.com/44733677/158035282-aa17e91b-c212-4169-88f2-ab56d37a164d.svg)

### ActivityPub
![ActivityPub-Light](https://user-images.githubusercontent.com/44733677/158035274-cc635b50-36cd-4c31-9a4f-979db16b9465.svg) ![ActivityPub-Dark](https://user-images.githubusercontent.com/44733677/158035275-3efceebf-4d6b-42a7-a4d7-1d9c75202d13.svg)

### HaxeFlixel
![HaxeFlixel-Light](https://user-images.githubusercontent.com/44733677/158035276-eeeb0150-b52e-44bf-9df6-673e7fec2a12.svg) ![HaxeFlixel-Dark](https://user-images.githubusercontent.com/44733677/158035277-38b03373-156c-4f8c-94b9-9f2dca4ca8f5.svg)

### AiScript
![AIScript_Light](https://user-images.githubusercontent.com/44733677/158035270-7953996a-98e4-49cc-bdea-8d8ad5b49bbd.svg) ![AIScript_Dark](https://user-images.githubusercontent.com/44733677/158035271-a5dc80ab-188d-433f-886e-c7694ae416b3.svg)

### Emacs Lisp (`el`)
![EmacsLisp_Light](https://user-images.githubusercontent.com/44733677/158035265-03b9017b-2f78-4f86-94f2-896adb3000f0.svg) ![EmacsLisp_Dark](https://user-images.githubusercontent.com/44733677/158035268-5728050c-f48a-4e93-85e1-87b4e79d477f.svg)

### GameMaker Studio (`gamemaker`)
![GameMaker_Studio](https://user-images.githubusercontent.com/44733677/158035272-c13764ca-a1c6-4565-acf4-6fb774f36656.svg)

### Unreal Engine (`ue`)
![UnrealEngine](https://user-images.githubusercontent.com/44733677/158035278-1f1a096e-15dc-4213-85e6-b56bb346f988.svg)

@tandpfun

**Comment by tandpfun** [comment]
Added in 28fb8ab

**Comment by ThatOneCalculator** [comment]
Wonderful, tysm!
