### ISSUE TITLE
[NEW ICON] Notion

### ISSUE THREAD

**Issue by Anirudh-A-V** [tandpfun/skill-icons#201]
### Skill Name

Notion

### Why?

It is a popular project management and note-taking software platform. It is very powerful and used by many developers and designers.

### Reference Image

![Notion-logo](https://user-images.githubusercontent.com/76550448/190110451-b65ce430-971b-4f24-b46f-15b2707f6e77.svg)

**Comment by alecames** [comment]
+1

**Comment by tandpfun** [comment]
Added in e67133b!
