### ISSUE TITLE
[NEW ICON] F# / FSharp

### ISSUE THREAD

**Issue by Kyocius** [tandpfun/skill-icons#205]
### Skill Name

F#

### Why?

F# is a excellent functional programming language running on .NET platform.

### Reference Image

![Fsharp](https://th.bing.com/th/id/R.d577f8f8cb402abd9ba7303a5a3ea119?rik=h9CnWf5znFBCuQ&riu=http%3a%2f%2fwww.roundcrisis.com%2fpresentations%2ffsharp_oss%2fimages%2ffsharp_logo.png&ehk=hln8SMzFnK5c2RpSl737XKszkzDZxv0%2fW4hN0KHY7fY%3d&risl=&pid=ImgRaw&r=0)

**Comment by A-Boring-Square** [comment]
Please Add This

**Comment by akhansari** [comment]
Hi @Kyocius, sorry I cannot find this icon. Is it really added?
