### ISSUE TITLE
[NEW ICON]Adobe  Lightroom Classic

### ISSUE THREAD

**Issue by yanboishere** [tandpfun/skill-icons#210]
### Skill Name

lightroom classic

### Why?

Also photographer use.

**Comment by sivelswhy** [comment]
You might consider changing your issue name to `[NEW ICON] Adobe Lightroom`

**Comment by yanboishere** [comment]
OK

**Comment by yanboishere** [comment]
I changed.

**Comment by yanboishere** [comment]
Awesome！Thanks for update.
