### ISSUE TITLE
[NEW ICON] Clion Pycharm

### ISSUE THREAD

**Issue by yanboishere** [tandpfun/skill-icons#213]
### Skill Name

Clion Pycharm

### Why?

These ide were also using popularity.

### Reference Image

![屏幕截图 2022-11-06 143907](https://user-images.githubusercontent.com/76860915/200157863-069f0284-eb45-4a32-8158-80f1dba607f7.png)

**Comment by tandpfun** [comment]
Added in e67133b!

**Comment by yanboishere** [comment]
love you guys！！！
