### ISSUE TITLE
[NEW ICON] AdonisJS

### ISSUE THREAD

**Issue by PedroHercules** [tandpfun/skill-icons#219]
### Skill Name

AdonisJS

### Why?

With AdonisJS, we don't need to worry about configuration or project structure, but with business rules. As a result, we become more productive. AdonisJS is an alternative to NestJS. Also, it is quite similar to laravel.. And I'm really enjoying learning about it.

**Comment by sivelswhy** [comment]
You might consider changing your issue name to `[NEW ICON] AdonisJS`

**Comment by sivelswhy** [comment]
Also, a duplicate of #189
