### ISSUE TITLE
[NEW ICON] Styled-components | Emotion | MUI (Material-UI)

### ISSUE THREAD

**Issue by lyanedev** [tandpfun/skill-icons#22]
### Skill Name

Styled-components, Emotion and MUI(Material-UI)

### Why?

Because they are really popular right now.

**Comment by ThatOneCalculator** [comment]
I'm not quite sure what emotion is (never even heard of it), and Material-UI isn't really a skill, more of a library.

**Comment by tandpfun** [comment]
Libraries can be skills, I think Material-UI is a great example of a skill that is also a library. Also, you don't have to know what all the suggested icons are! 😃 
Feel free to provide feedback on submitted icons, or let people know that their icons already exist, or do this in *super obvious cases* but leave the decisions on integration into the icon set up to me 💜

**Comment by ThatOneCalculator** [comment]
Gotcha. As per emotion, I was moreso trying to get at I couldn't even find anything about it online; I think I def could've phrased that better, given I wrote that comment close to 1 AM lol

**Comment by tandpfun** [comment]
All good! ~~go to sleep!~~

**Comment by ThatOneCalculator** [comment]
> All good! ~~go to sleep!~~

It's 5 PM now lmao, I'll try and get better sleep tonight tho

**Comment by tandpfun** [comment]
Added in 28fb8ab
