### ISSUE TITLE
[NEW ICON] Trello

### ISSUE THREAD

**Issue by Pyr33x** [tandpfun/skill-icons#221]
### Skill Name

Trello

### Why?

**Trello** is a web-based, Kanban-style, list-making application
It's very popular and used by many people

### Reference Image

![Trello](https://user-images.githubusercontent.com/83529331/197606570-55e2a274-46fe-43bd-98f1-77df6a64b95a.svg)

**Comment by josenobrec** [comment]
![trello-plain-wordmark](https://user-images.githubusercontent.com/53025031/236356766-13749ec9-142d-4cd3-8174-06bfa2144c90.svg)
![trello-plain](https://user-images.githubusercontent.com/53025031/236356767-b012e842-0ef5-4bf6-b8e1-374b33573419.svg)
