### ISSUE TITLE
[NEW ICON] OpenCV

### ISSUE THREAD

**Issue by dangalansky** [tandpfun/skill-icons#222]
### Skill Name

OpenCV

### Why?

This is a popular computer vision library used by C+ and Python developers. I'd love to add it!

### Reference Image

![OpenCV_logo_no_text](https://user-images.githubusercontent.com/97214702/197854543-c9bde9a3-5157-464b-a73a-14be3a950728.svg)

**Comment by skepfusky** [comment]
You might've forgotten to change your issue name to `[NEW ICON] OpenCV`

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!
