### ISSUE TITLE
[NEW ICON] dotenv

### ISSUE THREAD

**Issue by coren-frankel** [tandpfun/skill-icons#224]
### Skill Name

dotenv

### Why?

dotenv is a zero-dependency module that stores and loads environmental variables, added to projects but omitted from version control.

I realize this may seem like a weak skill, but I would argue it's more important that dev security tools as universal are worth consideration.

### Reference Image

![dotenv](https://user-images.githubusercontent.com/104476731/197982936-523fae2c-2853-46e4-9368-b336c539c527.svg)

**Comment by tandpfun** [comment]
Thanks for your suggestion! Unfortunately this isn't really a skill. We may consider it in the future!
