### ISSUE TITLE
[NEW ICON] LaTeX

### ISSUE THREAD

**Issue by yanboishere** [tandpfun/skill-icons#225]
### Skill Name

LaTeX

### Why?

写论文时可能需要

### Reference Image

![download](https://user-images.githubusercontent.com/76860915/200157896-6b06e20b-f2ef-4cfb-90d7-da857e128a98.png)

**Comment by yanboishere** [comment]
行

**Comment by yanboishere** [comment]
Your Traslated is right,that's i mean.

**Comment by yanboishere** [comment]
Picture was reference.

**Comment by tandpfun** [comment]
Already exists!
