### ISSUE TITLE
[NEW ICON] Bun

### ISSUE THREAD

**Issue by anish-mandal** [tandpfun/skill-icons#226]
### Skill Name

Bun

### Why?

Bun is a new, experimental and emerging JavaScript tool. It is actually a JavaScript runtime, bundler, transpiler and package manager which is a really convenient all in one tool for JavaScript developers. I think this skill is or will be acquired by many JS developers including me. They would like to add this skill to their github profile.

Website: [bun.sh](https://bun.sh)
Github: [github.com/oven-sh/bun](https://github.com/oven-sh/bun)

### Reference Image

![](https://user-images.githubusercontent.com/709451/182802334-d9c42afe-f35d-4a7b-86ea-9985f73f20c3.png)

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!
