### ISSUE TITLE
[NEW ICON] Replit

### ISSUE THREAD

**Issue by CubesterYT** [tandpfun/skill-icons#229]
### Skill Name

Replit

### Why?

For users who use replit to flex off, also to let others know they are on replit, and have projects there too.

### Reference Image

![image](https://user-images.githubusercontent.com/78769806/202031251-ba5e2bf3-de32-411c-806b-878917533a6a.png)

**Comment by tandpfun** [comment]
Added in 59059d9d1a2c092696dc66e00931cc1181a4ce1f!
