### ISSUE TITLE
[NEW ICON] Cypress

### ISSUE THREAD

**Issue by mohsinfarabi** [tandpfun/skill-icons#232]
### Skill Name

cypress

### Why?

Cypress is a purely JavaScript-based front-end testing tool built for the modern web. It aims to address the pain points developers or QA engineers face while testing an application

### Reference Image

![16414264681536211770](https://user-images.githubusercontent.com/14385156/202866538-a43aaaa0-b089-46c4-9e11-499ab8110f02.svg)

**Comment by tandpfun** [comment]
Added in e67133b!
