### ISSUE TITLE
[BUG REPORT] Icons not loading on Repl.it

### ISSUE THREAD

**Issue by 1RB** [tandpfun/skill-icons#235]
### The bug

Icon does not render when link is pasted

### Steps to reproduce

1. Create a README.md file on https://repl.it and paste an icon inside the readme file

### Any extra info

![image](https://user-images.githubusercontent.com/86501179/202927515-19ce8294-b61b-48cb-ae98-2f2b15b4576b.png)
![image](https://user-images.githubusercontent.com/86501179/202927517-4f044460-d8c8-4ace-8f24-a1edb2888cd1.png)

**Comment by tandpfun** [comment]
Maybe replit doesn't support svgs? You could try adding a `&.svg` to the end of the url and testing if it works. Otherwise, this is more of a replit issue.
