### ISSUE TITLE
[NEW ICON] Apache web server

### ISSUE THREAD

**Issue by DavKiller** [tandpfun/skill-icons#239]
### Skill Name

Apache

### Why?

Apache is a very used web server and I think its a good icon to add.

### Reference Image

![Apache_HTTP_Server_Logo_(2016)](https://user-images.githubusercontent.com/65242580/204152273-da055b54-e90a-4e39-88cb-90cadf8624b9.svg)

**Comment by kuroji-fusky** [comment]
I hate to break it to ya, but this is a duplicate of #186

**Comment by DavKiller** [comment]
Sorry I didn't know it
