### ISSUE TITLE
[NEW ICON] Ubuntu, Kali Linux, Debian

### ISSUE THREAD

**Issue by callumisdumb** [tandpfun/skill-icons#24]
### Skill Name

Ubuntu, Kali Linux, Debian

### Why?

Popular OS for servers + personal use

### Reference Image

https://iconape.com/wp-content/files/ec/369246/svg/ubuntu-logo-icon-png-svg.png
https://seeklogo.com/images/K/kali-linux-logo-0EB0B3A81B-seeklogo.com.png
https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Openlogo-debianV2.svg/1200px-Openlogo-debianV2.svg.png

**Comment by ThatOneCalculator** [comment]
Read: https://github.com/tandpfun/skill-icons/issues/19#issuecomment-1065826985

These are all Linux Distros, NOT OSes unto themselves, and a Linux icon already exists.

**Comment by callumisdumb** [comment]
@ThatOneCalculator (wouldn't let me quote reply for some reason)

fair nuff! didn't see the linux icon (aaa), will close this up for now :)
