### ISSUE TITLE
[NEW ICON] Nix

### ISSUE THREAD

**Issue by LudovicoPiero** [tandpfun/skill-icons#244]
### Skill Name

Nix

### Why?

Nix is a package manager and build system that parses reproducible build instructions specified in the [Nix Expression Language](https://nixos.wiki/wiki/Nix_Expression_Language), a pure functional language with lazy evaluation.

### Reference Image

![image](https://user-images.githubusercontent.com/44255157/205443777-3243ccd8-3911-4973-b48a-e39eb488c9fd.png)
Svg can be found [here](https://github.com/NixOS/nixos-artwork/blob/c1dc75611042b57a385c80495d3728724c35cfee/logo/nix-snowflake.svg)

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!
