### ISSUE TITLE
[NEW ICON] MySQL

### ISSUE THREAD

**Issue by awesomecosmos** [tandpfun/skill-icons#245]
### Skill Name

MySQL

### Why?

MySQL is widely used across industry for relational database management.

### Reference Image

![mysql-ar21](https://user-images.githubusercontent.com/56360465/205451176-eda6e191-5a06-45e5-8aed-41f2c63c4968.svg)

**Comment by kuroji-fusky** [comment]
It seems that **MySQL** is already added as an icon, make sure to double-check the available icons before adding an issue!
```md
![](https://skillicons.dev/icons?i=mysql)
```
![](https://skillicons.dev/icons?i=mysql)
