### ISSUE TITLE
[NEW ICON] Anaconda

### ISSUE THREAD

**Issue by awesomecosmos** [tandpfun/skill-icons#246]
### Skill Name

Anaconda

### Why?

Anaconda is a distribution for Python and R packages and is a very popular scientific programming environment.

### Reference Image

![icons8-anaconda](https://user-images.githubusercontent.com/56360465/205451260-cfed7f0e-bd3b-4d0b-8c72-1862dbdca629.svg)

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!
