### ISSUE TITLE
[BUG REPORT] Rust icon does not obey theming

### ISSUE THREAD

**Issue by Sir-Photch** [tandpfun/skill-icons#248]
### The bug

The Background of the rust-icon stays orange, regardless of what theme is used. This does not fit the theming of other icons.

### Steps to reproduce

![foo](https://skillicons.dev/icons?i=rust,linux,ros,github,bash,latex&perline=3&theme=light)

**Comment by tandpfun** [comment]
Not all icons use themes! We prefer to use non-themed icons for logos where possible, unless the logo's colors don't look good on both black and white backgrounds or arent squares.
