### ISSUE TITLE
[NEW ICON] Empty Icon

### ISSUE THREAD

**Issue by norwd** [tandpfun/skill-icons#249]
### Skill Name

Empty

### Why?

To add an empty space in the image to separate sections.

### Reference Image

Should just be an empty, transparent square.

**Comment by Benricheson101** [comment]
If you try to use an icon that doesn't exist, it'll display a blank space. Try using something like `empty`.

**Comment by norwd** [comment]
> If you try to use an icon that doesn't exist, it'll display a blank space. Try using something like `empty`.

I just tried `https://skillicons.dev/icons?i=js,html,css,empty,wasm`, and it works exactly as I wanted. Thanks!

[![https://skillicons.dev/icons?i=js,html,css,empty,wasm](https://skillicons.dev/icons?i=js,html,css,empty,wasm)](https://skillicons.dev/icons?i=js,html,css,empty,wasm)
