### ISSUE TITLE
sklearn

### ISSUE THREAD

**Issue by Ignacio-Ibarra** [tandpfun/skill-icons#250]
### Skill Name

scikit-learn, xgboost, lightgbm

### Why?

The are most used machine learning frameworks 

### Reference Image

![sklearn](https://user-images.githubusercontent.com/64967345/207378569-825d15aa-766d-4d0b-8df6-71ebc4b011d4.png)
![xgboost](https://www.google.com/imgres?imgurl=https%3A%2F%2Fmljar.com%2Fimages%2Fmachine-learning%2Fxgboost_v2.png&imgrefurl=https%3A%2F%2Fmljar.com%2Fmachine-learning%2Fcatboost-vs-xgboost%2F&tbnid=oDf_uu1SZSLW_M&vet=12ahUKEwif6eHz9_b7AhUtvJUCHQbMCPAQMygDegUIARDEAQ..i&docid=MMAK-FbtSIclUM&w=435&h=176&q=xgboost%20icon&ved=2ahUKEwif6eHz9_b7AhUtvJUCHQbMCPAQMygDegUIARDEAQ)

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!
