### ISSUE TITLE
[NEW ICON] Docker Light

### ISSUE THREAD

**Issue by eminarikan** [tandpfun/skill-icons#253]
### Skill Name

Docker

### Why?

Skill-icons' way themed light Docker icon.

### Reference Image

![Docker-Light](https://user-images.githubusercontent.com/41510726/208197008-51f640ed-a7ad-4146-9cf7-0435db47fe24.svg)

**Comment by tandpfun** [comment]
Currently, themed icons are only used when the logo does not provide a background or is not visible on both black and white. Thank you for the suggestion, though!
