### ISSUE TITLE
[NEW ICON] Git Light

### ISSUE THREAD

**Issue by eminarikan** [tandpfun/skill-icons#254]
### Skill Name

Git Light

### Why?

Skill-icons' way themed light Git icon.

### Reference Image

![Git-Light](https://user-images.githubusercontent.com/41510726/208197469-2191c234-15ee-4e9a-8a1a-ca789e0679dc.svg)

**Comment by tandpfun** [comment]
Currently, themed icons are only used when the logo does not provide a background or is not visible on both black and white. Thank you for the suggestion, though!
