### ISSUE TITLE
[NEW ICON] HTML Light

### ISSUE THREAD

**Issue by eminarikan** [tandpfun/skill-icons#255]
### Skill Name

HTML Light

### Why?

Skill-icons' way themed light HTML icon.

### Reference Image

![HTML-Light](https://user-images.githubusercontent.com/41510726/208198107-1e857422-c39c-4bd6-8d21-ede70ff5d31c.svg)

**Comment by tandpfun** [comment]
Currently, themed icons are only used when the logo does not provide a background or is not visible on both black and white. Thank you for the suggestion, though!
