### ISSUE TITLE
[NEW ICON] P5.js

### ISSUE THREAD

**Issue by Rclarkeweb** [tandpfun/skill-icons#258]
### Skill Name

P5.js

### Why?

P5.js is a JavaScript library for creative coding and really easy to use.

### Reference Image

![p5 js](https://user-images.githubusercontent.com/108008511/209164536-08a972f6-f502-4fc8-bca6-1d7fc68ee1d2.png)

**Comment by tandpfun** [comment]
✅ Added in ce11465!
