### ISSUE TITLE
[NEW ICON] Gitea

### ISSUE THREAD

**Issue by TerrificTable** [tandpfun/skill-icons#274]
### Skill Name

Gitea

### Why?

Gitea is like GitHub or GitLab, no other "*big*" reason

**Comment by TerrificTable** [comment]
forgot the reference image: 
![image](https://user-images.githubusercontent.com/85793326/211173526-3ac24776-9484-4116-8495-a0bff8fd26ec.png)

**Comment by tandpfun** [comment]
Thank you for the suggestion! Unfortunately it isn't really a skill and won't be added at this time.
