### ISSUE TITLE
Adobe Illustrator is out of alphabetical order

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#29]
I'd PR but im on mobile

![Screenshot_20220312-180709.jpg](https://user-images.githubusercontent.com/44733677/158041764-26e85067-0f7a-4fae-bd76-6007b84e4619.jpg)

**Comment by tandpfun** [comment]
The short name is, but it's in alphabetical order of the file name - so `Illustrator`

**Comment by ThatOneCalculator** [comment]
Ah gotcha
