### ISSUE TITLE
[NEW ICON] Skill Name

### ISSUE THREAD

**Issue by xhundo** [tandpfun/skill-icons#295]
### Skill Name

Babel, Postman

### Why?

It's popular in web development, makes the profile stand out with the full stack. 

### Reference Image

![babel](https://user-images.githubusercontent.com/98115017/215364855-3bb2dad3-38b5-4d2e-96f7-2d613910d743.svg)
![postman-icon-svgrepo-com](https://user-images.githubusercontent.com/98115017/215364856-e2e94c87-3c06-44be-82c0-3da864428c39.svg)

**Comment by Pyr33x** [comment]
Postman duplicate #114

**Comment by tandpfun** [comment]
Both have been added from separate issues. Thank you for the suggestion!
