### ISSUE TITLE
[BUG REPORT] Bug LinkedIn icon bad looking

### ISSUE THREAD

**Issue by Jirafey** [tandpfun/skill-icons#296]
### The bug

LinkedIn icon has white outlines that make it seem horrible

**Comment by Pyr33x** [comment]
It's okay 🤷🏻

**Comment by tandpfun** [comment]
Could you provide a screenshot of the issue?

**Comment by Jirafey** [comment]
> Could you provide a screenshot of the issue?

Ill take a look at it, on phone its fine

**Comment by Jirafey** [comment]
nevermind its ok
