### ISSUE TITLE
[NEW ICON] Mongoose

### ISSUE THREAD

**Issue by haldaranup** [tandpfun/skill-icons#298]
### Skill Name

Mongoose

### Why?

Mongoose is a JavaScript object-oriented programming library that creates a connection between MongoDB and the Node.js JavaScript runtime environment.

**Comment by kuroji-fusky** [comment]
Duplicate of #203, and besides you haven't provided a reference image as well

**Comment by haldaranup** [comment]
> Duplicate of #203, and besides you haven't provided a reference image as well

Oh, closing this issue😶

**Comment by haldaranup** [comment]
Duplicate issue
