### ISSUE TITLE
[NEW ICON] Linux, open source tools and others

### ISSUE THREAD

**Issue by urienix** [tandpfun/skill-icons#3]
**Skill Name**
Linux, Wordpress, Nginx, Jenkins, Sass, Bash

**Why?**
Some are popular, others are very common in the server area or web development.

**Comment by tandpfun** [comment]
Added in most in #2fae3ac, linux is in #5 which I'll review later today.

**Comment by urienix** [comment]
wow! that was fast. I'm happy, thanks for adding them.
