### ISSUE TITLE
[NEW ICON] WebStorm

### ISSUE THREAD

**Issue by mrEckendonk** [tandpfun/skill-icons#303]
### Skill Name

WebStorm

### Why?

It's a great IDE made by JetBrains, has more functions than VSCode, and can automize a lot. Better code quality.

JetBrains IDE's is made to make a developer's life a lot easier. It changed mine for sure and want to encourage others to use it.

### Reference Image

![WebStorm_Icon](https://user-images.githubusercontent.com/30936842/216797813-3687ba63-2d26-4e98-a642-24699fe0689f.svg)

**Comment by tandpfun** [comment]
Added in e67133b!
