### ISSUE TITLE
[NEW ICON] Skill Name

### ISSUE THREAD

**Issue by fable147** [tandpfun/skill-icons#306]
### Skill Name

MSSQL

### Why?

tihsi is widely use by developer

### Reference Image

![microsoft-sql-server-logo-750x338](https://user-images.githubusercontent.com/54307844/216844743-6a98d759-4585-4d30-bc41-64fb697f3c27.png)

**Comment by kuroji-fusky** [comment]
Someone already requested SQL Server on #149.
