### ISSUE TITLE
[NEW ICON] Ktor.io

### ISSUE THREAD

**Issue by auguwu** [tandpfun/skill-icons#31]
### Skill Name

ktor.io

### Why?

It's popular among the Kotlin ecosystem to provide a fast, and safe HTTP server/client.

### Reference Image

:pensive: sorry just a base64 blob of it D:

`data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMDIiIGhlaWdodD0iNDgiIHZpZXdCb3g9IjAgMCAxMDIgNDgiPjxnIGZpbGw9Im5vbmUiPjxwYXRoIGZpbGw9IiNGMjY2MzYiIGQ9Ik0xNi4wMDQgMEwwIDE2LjAwNCAxNi4wMDQgMzJWMTYuMDA0SDMyeiIvPjxwYXRoIGZpbGw9IiM2MzczRkYiIGQ9Ik00OCAzMS45OTZMMzEuOTk2IDE2djE1Ljk5NkgxNkwzMS45OTYgNDh6Ii8+PHBhdGggZmlsbD0iIzI3MjgyQyIgZD0iTTMyIDE2SDE2djE2aDE2em0yOS43NTcgMTUuNzd2LTQuNDEybDEuNDYzLTEuNzIgNC4yODcgNi4xMzJoMy43MDRsLTUuNzYtOC4xMTQgNS4zODEtNi4zMjNoLTMuNDM4bC01LjQ1MyA2LjQ4M2gtLjE4NHYtNi40ODNoLTMuMDlWMzEuNzdoMy4wOXptMTEuNzI1LTEzLjY0NnYyLjczaC0xLjc2djIuMjEyaDEuNzZ2NS43MzNjMCAyLjE0IDEuMDg1IDMuMDExIDMuODI3IDMuMDExYTguNSA4LjUgMCAwMDEuNDk0LS4xM3YtMi4xNTFhNy4yIDcuMiAwIDAxLS44OC4wNWMtMS4wMTMgMC0xLjQ2My0uNDYtMS40NjMtMS40NXYtNS4wNjNoMi4zNDN2LTIuMjExSDc2LjQ2di0yLjczMWgtMi45Nzh6TTg2LjIxMSAzMmMzLjQ2OCAwIDUuNTU2LTIuMTQgNS41NTYtNS43NDMgMC0zLjU3MS0yLjExOC01Ljc0Mi01LjU1Ni01Ljc0MnMtNS41NTYgMi4xOC01LjU1NiA1Ljc0MmMwIDMuNTkyIDIuMDg3IDUuNzQzIDUuNTU2IDUuNzQzem0wLTIuMzAxYy0xLjU5NiAwLTIuNDk3LTEuMjYtMi40OTctMy40NDIgMC0yLjE2LjkxLTMuNDMxIDIuNDk3LTMuNDMxIDEuNTc1IDAgMi40OTYgMS4yNyAyLjQ5NiAzLjQzMSAwIDIuMTgxLS45MSAzLjQ0Mi0yLjQ5NiAzLjQ0MnptNy45OSAyLjA3aDIuOTc4di02LjE2MmMwLTEuNTUgMS4xMTUtMi41MDEgMi43NDItMi41MDEuNDgxIDAgMS4xNzcuMDggMS40MTIuMTZ2LTIuNTYxYy0uMjU1LS4wOC0uNzU3LS4xMy0xLjE2Ni0uMTMtMS40MzIgMC0yLjU5OS44My0yLjg5NiAxLjkzaC0uMTg0di0xLjc1aC0yLjg4NVYzMS43N3oiLz48L2c+PC9zdmc+Cg==`

**Comment by ThatOneCalculator** [comment]
Here you go, you sussy little baka >w<

![Ktor-Light](https://user-images.githubusercontent.com/44733677/158043124-dd95ec3c-03c1-44bf-9b38-da617cf1aa93.svg) ![Ktor-Dark](https://user-images.githubusercontent.com/44733677/158043125-05093997-2029-4ce3-ae17-63b92debc976.svg)

**Comment by ThatOneCalculator** [comment]
CCing @tandpfun (sorry for relentlessly pinging you) since it's now an icon

**Comment by tandpfun** [comment]
> CCing @tandpfun (sorry for relentlessly pinging you) since it's now an icon

No need to ping, I get an email on issues & comments already (and I'll check it when I have time). Thank you for designing em tho!!

**Comment by ThatOneCalculator** [comment]
Ah yea i forgot a lot of people have git emails on lol :D

**Comment by tandpfun** [comment]
Added in ecdf58df14ebd60c0030a6f3beb5641f605ae30b
