### ISSUE TITLE
[NEW ICON] Cypress

### ISSUE THREAD

**Issue by josephburgess** [tandpfun/skill-icons#331]
### Skill Name

Cypress

### Why?

Popular front end testing framework

### Reference Image

<img width="100" alt="image" src="https://user-images.githubusercontent.com/4661986/220535884-9f832dfb-0209-4670-8bfb-7d7067a8af7c.png">

**Comment by Sls0n** [comment]
Duplicate of #232

**Comment by tandpfun** [comment]
Added in e67133b!
