### ISSUE TITLE
[NEW ICON] Roblox Studio

### ISSUE THREAD

**Issue by ImAvafe** [tandpfun/skill-icons#335]
### Skill Name

Roblox Studio

### Why?

There are other game engine icons here, including some less prevalent than Roblox Studio. Roblox creators are increasingly integrating with Git and Github with the rise of software like [Rojo](https://rojo.space/).

I know it probably wouldn't be a priority, but I'd like to have it on my profile.

### Reference Image

![Roblox_Studio_Logo](https://user-images.githubusercontent.com/65048459/221366410-d593f6a9-a72b-49c3-8de3-c80e02c6ca0a.svg)

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!

**Comment by ImAvafe** [comment]
tysm!
