### ISSUE TITLE
[NEW ICON] Linux distributions

### ISSUE THREAD

**Issue by jarod25** [tandpfun/skill-icons#346]
### Skill Name

ubuntu, debian, arch, manjaro, fedora, mint, ...

### Why?

Adding Linux distro icons to a list of icons project on GitHub can be beneficial for several reasons:

Completeness: Linux is a widely used operating system, and including its icons in the list can make it more comprehensive and useful for developers and users who work with Linux.

Accessibility: Having Linux distro icons readily available can make it easier for users to navigate and use Linux-based systems, especially for those who are new to the platform.

Contribution: Including Linux distro icons in the project can also encourage contributions from Linux enthusiasts who are passionate about improving the user experience of Linux-based systems.

Consistency: Including Linux distro icons in the list can also help maintain consistency in the overall design and user experience of applications and websites that use the icons.

Overall, adding Linux distro icons to a list of icons project on GitHub can be a valuable addition for the community, providing accessibility and consistency while encouraging contributions and making the project more complete.

**Comment by sahil-sagwekar2652** [comment]
### Reference Image for Arch
![Arch Linux logo](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Archlinux-logo-standard-version.png/1920px-Archlinux-logo-standard-version.png)

**Comment by SANAGOdev** [comment]
its a real good idea thanks

**Comment by aarikpokras** [comment]
## SVG reference image for Arch Linux
![Arch Linux](https://github.com/tandpfun/skill-icons/assets/85502246/e63ee929-5094-4dd3-872f-39019b71bb31)

**Comment by tandpfun** [comment]
Added in e67133b!
