### ISSUE TITLE
[NEW ICON] Appwrite

### ISSUE THREAD

**Issue by Meldiron** [tandpfun/skill-icons#35]
### Skill Name

Appwrite

### Why?

Appwrite is slowly becoming more and more popular backend as a service, similar to Firebase. Since Firebase is already on the list, I believe experience with a BaaS is a skill. Considering Appwite is open source, just like Skill Icons, I think adding Appwrite into the skills icons list would be a great addition.

### Reference Image

https://appwrite.io/assets

I can create a PR, but as non-designer I would love some feedback on the structure. Icons I have ready are:

<img width="583" alt="CleanShot 2022-03-13 at 08 26 01@2x" src="https://user-images.githubusercontent.com/19310830/158049864-bb1231c3-a79e-45e7-91aa-d93ed3de1986.png">

Opened questions:
- Which row should the icon use? First would be same for dark&light, second is using Skill Icons dark&light background, and third is using Appwrite color pallete only
- Is padding between icon and background correct? The square is 256x256, and the icon is 193x129.

**Comment by tandpfun** [comment]
I love the first one! Will be added shortly.

**Comment by tandpfun** [comment]
Added in ecdf58df14ebd60c0030a6f3beb5641f605ae30b, thank you!!
