### ISSUE TITLE
[NEW ICON] Ubuntu

### ISSUE THREAD

**Issue by LilScottyPippen** [tandpfun/skill-icons#351]
### Skill Name

Ubduntu

### Why?

Ubuntu is a Linux distribution based on Debian and composed mostly of free and open-source software.

### Reference Image

**1.0 Version white:**
![Frame 7](https://user-images.githubusercontent.com/126200705/222957389-a9b7c51a-b3b4-4b95-bbdb-d496aa8b23c5.svg)
**1.0 Version dark:**
![Frame 6](https://user-images.githubusercontent.com/126200705/222957397-ee3b2f52-5445-442a-a0e9-cf88813ae248.svg)
**2.0 Version white**
![Frame 4](https://user-images.githubusercontent.com/126200705/222957423-dd158be3-ca93-4426-be0b-a01d8e289db3.svg)
**2.0 Version dark**
![Frame 5](https://user-images.githubusercontent.com/126200705/222957453-dc4297b8-14e3-4ec2-9f65-fd0b83a918fc.svg)

**Comment by mr-loop-1** [comment]
this

**Comment by tandpfun** [comment]
Added in e67133b!
