### ISSUE TITLE
[NEW ICONS] [COMPLETED 🥳] Electron, QT, GTK, Tauri, Azul, Pug

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#37]
### Skill Name

Electron, QT, GTK, Tauri, Azul, Pug

### Why?

Electron, QT, GTK, Tauri, Azul: very popular desktop gui frameworks
Pug: popular html abstractor

### Pug
![Pug-Light](https://user-images.githubusercontent.com/44733677/158069425-f79c620e-3e9d-47a2-b9d0-b2fc403e470d.svg)

### Tauri
![Tauri-Light](https://user-images.githubusercontent.com/44733677/158069437-13d1d1ac-a8fc-4291-a259-fa5a4eabb92d.svg)

### GTK
![GTK-Light](https://user-images.githubusercontent.com/44733677/158070081-728e8e6f-1e53-4b55-b51e-f13f85dce51f.svg)

### QT
![QT-Light](https://user-images.githubusercontent.com/44733677/158069451-f0ea3a4b-cdd5-432e-9796-51e8f48e400b.svg)

# Colored icons
### Electron
![Electron](https://user-images.githubusercontent.com/44733677/158069459-a20002a0-9179-4e05-8ca1-060768d1351f.svg)

### Azul
![Azul](https://user-images.githubusercontent.com/44733677/158069464-f3a011b2-df58-44bc-9e35-e06843823244.svg)

**Comment by tandpfun** [comment]
Added in ecdf58df14ebd60c0030a6f3beb5641f605ae30b, thank you!

**Comment by tandpfun** [comment]
The azul logo svg (the one here, and the one on their website) is very weirdly formatted and might look a bit off in the icon form, as I had to make it compatible.
