### ISSUE TITLE
[NEW ICON] HTMX

### ISSUE THREAD

**Issue by blue-hexagon** [tandpfun/skill-icons#373]
### Skill Name

HTMX

### Why?

Because it's popular (11k ⭐) and missing.

[Github Repo, HTMX](https://github.com/bigskysoftware/htmx)

### Reference Image

![htmx_logo 1](https://user-images.githubusercontent.com/26361520/226900990-714d1101-6bfb-46c7-8421-f40cf38b13d0.png)

**Comment by KaiyuanMa** [comment]
Would love to see htmx

**Comment by tandpfun** [comment]
Added in e67133b!
