### ISSUE TITLE
[ISSUE] StyledComponents icon is broken

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#38]
Most likely caused by StyledComponents using a PNG icon.

![image](https://user-images.githubusercontent.com/44733677/158069825-9573c8d2-f5f5-447b-aac5-90159a7c62ea.png)

**Comment by tandpfun** [comment]
Yeah... It's using an emoji because I couldn't find an svg of the logo.

**Comment by ThatOneCalculator** [comment]
> Yeah... It's using an emoji because I couldn't find an svg of the logo.

There doesn't seem to be an existing SVG of the Apple-styled 💅 emoji, maybe it should be removed for now given it's broken?

**Comment by ThatOneCalculator** [comment]
Potentially closed by #47
