### ISSUE TITLE
[NEW ICON] OpenShift

### ISSUE THREAD

**Issue by vbelouso** [tandpfun/skill-icons#39]
Skill Name
OpenShift

Why?
Popular enterprise-ready Kubernetes container platform

Reference Image
in attachment

![Product_Icon-Red_Hat-OpenShift-RGB-256](https://user-images.githubusercontent.com/89217163/158074283-9000d161-de51-4f4a-83c0-a39bdc13cd4a.svg)
![Product_Icon-Red_Hat-OpenShift-RGB-38](https://user-images.githubusercontent.com/89217163/158074286-fe2a9795-be8f-494c-8dac-d187afb3e6c0.svg)

**Comment by tandpfun** [comment]
Added in 1bfaa272b1632ec9c26a6e4a1d2cb01fce981516, thank you!
