### ISSUE TITLE
[NEW ICON] Linux Distros (Ubuntu, Debian, Fedora, Kali)

### ISSUE THREAD

**Issue by R-Rothrock** [tandpfun/skill-icons#404]
### Skill Name

Ubuntu, Debian, Fedora, Kali, Redhat, Archlinux, etc.

### Why?

I know I'd use it, and I'm sure I'm not the only one.

**Comment by eduarddejong** [comment]
I would love to see the Arch logo. 💙

**Comment by R-Rothrock** [comment]
For real
