### ISSUE TITLE
[NEW ICONS] [COMPLETED 🥳] Apollo, Gherkin, Rocket, Fortran

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#41]
### Skill Name

Apollo, Gherkin, Rocket, Fortran

### Why?

Apollo: very popular GraphQL client/framework
Rocket: very popular Rust web framework
Gherkin: popular templating language
Fortran: some of us boomers still exist (actually still widely used in legacy programs)

### Completed icons

![Apollo](https://user-images.githubusercontent.com/44733677/158098500-f9eb107f-e063-4492-a53d-117c73da04b0.svg)
![Rocket](https://user-images.githubusercontent.com/44733677/158098470-32fab0da-ab30-45e2-9f1a-dbfe2bf88ef5.svg)
![Gherkin-Light](https://user-images.githubusercontent.com/44733677/158098473-6aab6bc9-1ed4-4445-8540-64c691915b4c.svg)
![Fortran](https://user-images.githubusercontent.com/44733677/158107264-741ec734-21e9-45bd-878a-ed3018057624.svg)

**Comment by tandpfun** [comment]
Added in 9fb9ca1

**Comment by ThatOneCalculator** [comment]
Ty! Guessing they'll show up in the readme soon :P

**Comment by tandpfun** [comment]
ooops I'll do that tomorrow unless u can pr em and the other icon I added

**Comment by ThatOneCalculator** [comment]
See #44
