### ISSUE TITLE
[NEW ICON] PyCharm

### ISSUE THREAD

**Issue by Kyomari** [tandpfun/skill-icons#411]
### Skill Name

Pycharm

### Why?

PyCharm is an Integrated Development Environment (IDE) for Python programming language, developed by JetBrains. It provides a rich set of tools and features to facilitate the development of Python applications, including code completion, code inspection, debugging, testing, and version control integration. 

PyCharm is a very popular IDE used by many Python developers.

### Reference Image

![A4BCE566-0330-4E3E-9829-E4FD611321D8](https://user-images.githubusercontent.com/125655373/235873131-bd6ff531-d262-4e5b-91f5-ac5f3d82bde2.jpeg)

**Comment by tandpfun** [comment]
Added in e67133b!
