### ISSUE TITLE
[NEW ICON] Ansible

### ISSUE THREAD

**Issue by vbelouso** [tandpfun/skill-icons#43]
### Skill Name

Ansible

### Why?

Popular automation platform

### Reference Image

![Product_Icon-Red_Hat-Ansible-RGB](https://user-images.githubusercontent.com/89217163/158364512-e81caf00-df4a-4ec7-9b1b-a2cb0c80a0ea.svg)

**Comment by tandpfun** [comment]
Added in 9fb9ca1
