### ISSUE TITLE
[NEW ICON] ejs

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [tandpfun/skill-icons#446]
### Skill Name

ejs

### Why?

It should be added as an icon because it is a commonly used package.

### Reference Image

https://github.com/mde/ejs-site/blob/main/assets/images/icon/256x256.png

**Comment by Deveroonie** [comment]
agreed

**Comment by WilliamDavidHarrison** [comment]
This project doesn't seem to be actively maintained.
