### ISSUE TITLE
[NEW ICON] Ubuntu

### ISSUE THREAD

**Issue by Reed0ne** [tandpfun/skill-icons#452]
### Skill Name

ubuntu

### Why?

Ubuntu is very popular among Windows users, basically it is an operating system, built from a Linux nucleo. Based on Debian and uses Gnome

### Reference Image

https://cdn.icon-icons.com/icons2/1508/PNG/512/distributorlogoubuntu_103999.png

**Comment by tandpfun** [comment]
Added in e67133b!
