### ISSUE TITLE
[NEW ICON] Ubuntu/Distros Linux

### ISSUE THREAD

**Issue by JoaoLeo** [tandpfun/skill-icons#474]
### Skill Name

Ubuntu

### Why?

Ubuntu is one of the most widely used Linux distributions, and it would be interesting to have its icon as well as icons of other distros.

### Reference Image

![UbuntuCoF svg](https://github.com/tandpfun/skill-icons/assets/87776853/e130c42d-a4aa-4c53-a1d2-aaf8e3873b2b)

**Comment by tandpfun** [comment]
Added in e67133b!
