### ISSUE TITLE
[NEW ICON] Redux

### ISSUE THREAD

**Issue by raulmarindev** [tandpfun/skill-icons#49]
### Skill Name

Redux

### Why?

Most used State Container for JS Apps

### Reference Image

https://d33wubrfki0l68.cloudfront.net/0834d0215db51e91525a25acf97433051f280f2f/c30f5/img/redux.svg

**Comment by tandpfun** [comment]
Added in 47e2fb9bc1353315f589ad5ce992b4f7debf2e48
