### ISSUE TITLE
[NEW ICON] Windows/MacOS

### ISSUE THREAD

**Issue by merive** [tandpfun/skill-icons#50]
### Skill Name

Windows/MacOS

### Why?

This repository already has Linux Icon, I think Windows and MacOS Icons will be useful.

### Reference Image

<div>
    <img src="https://user-images.githubusercontent.com/52623720/158844842-958b143c-c34f-4e76-baaa-423310f66241.svg" width="84">
<img src="https://user-images.githubusercontent.com/52623720/158845279-a59b8c3f-7395-4806-a639-a8639cf10379.svg" width="84">
</div>

**Comment by ThatOneCalculator** [comment]
Windows and macOS aren't skills -- neither is the Linux desktop. The OSes listed (Linux, BSD, Plan9) are all targeted for servers.

**Comment by LeifWritesCode** [comment]
Apologies for necroing this. I disagree that Windows/macOS development aren't skills. In the same way that knowledge of the Linux kernel and syscalls are widely considered a skill, development for Win32 ('Windows', as opposed to, say, dotnet) and the Apple ecosystem are certainly considered to be skills. I suppose I'm curious how you arrive at Linux server development/administration being a skill, but Windows/Apple development/administration not?
