### ISSUE TITLE
[NEW ICON] Typescript

### ISSUE THREAD

**Issue by andersonwea** [tandpfun/skill-icons#502]
### Skill Name

Typescript

### Why?

It's popular superset for javascript developers

**Comment by shake551** [comment]
there is already
https://github.com/tandpfun/skill-icons/blob/main/icons/TypeScript.svg
<img width="258" alt="Screenshot 2023-08-04 at 8 39 21" src="https://github.com/tandpfun/skill-icons/assets/73379887/dfc2e08f-8989-4d55-bc28-eda6d11dc087">

**Comment by andersonwea** [comment]
Thanks a lot!
