### ISSUE TITLE
[NEW ICON] Apache Cassandra

### ISSUE THREAD

**Issue by ServOKio** [tandpfun/skill-icons#51]
### Skill Name

ApacheCassandra (or just cassandra)

### Why?

There are icons with Redis, Postgresql, MongoDB and others - why not 🤷‍♀️? + cassandra has an `svg` template

### Reference Image
`Background: #FFFFFF`

![cassandra](https://user-images.githubusercontent.com/51263003/158881932-172c41c4-5240-4e85-8594-ef94cfa9fe7a.png)

https://upload.wikimedia.org/wikipedia/commons/5/5e/Cassandra_logo.svg
<img src="https://upload.wikimedia.org/wikipedia/commons/5/5e/Cassandra_logo.svg" alt="cassandra"/>

**Comment by tandpfun** [comment]
Added in 47e2fb9bc1353315f589ad5ce992b4f7debf2e48
