### ISSUE TITLE
[NEW ICONS] [COMPLETED 🥳] Perl, Julia, Astro

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#52]
### Skill Name

Perl, Julia, Astro

### Why?

- Perl: very popular programming language
- Julia very popular programming language
- Astro: very popular web framework

##### Perl
![Perl-Light](https://user-images.githubusercontent.com/44733677/159095851-3a14fc4a-db4c-4694-87b9-c16d7d5ed8c4.svg)
##### Julia
![Julia-Light](https://user-images.githubusercontent.com/44733677/159095855-75f6b4ee-038a-41d5-ab90-8963779dcee3.svg)

##### Astro
![Astro](https://user-images.githubusercontent.com/44733677/159095862-42ce0680-68c8-4b47-9913-20a56e3d0693.svg)

**Comment by tandpfun** [comment]
Added in 47e2fb9bc1353315f589ad5ce992b4f7debf2e48
