### ISSUE TITLE
[NEW ICON] Instagram, Twitter, LinkedIn

### ISSUE THREAD

**Issue by omerfarukdag** [tandpfun/skill-icons#53]
### Skill Name

Instagram, Twitter, LinkedIn

### Why?

Why not social media icons when there are even code editor icons? At least the LinkedIn icon should be added.

### Reference Image

![image](https://user-images.githubusercontent.com/45299198/159114227-96976f3d-70e4-43cb-9592-2524bfccabf8.png)

**Comment by ThatOneCalculator** [comment]
Because using editors require skill? (Esp emacs/vim). This isnt relevant at all.

**Comment by tandpfun** [comment]
I already made these 😄 
Usage of these platforms do require skill, especially for social media managing for companies, hiring, etc. Also just a nice icon to have if people want to use them as buttons.

**Comment by ThatOneCalculator** [comment]
Ig, but the way the issue was worded made it seem like OP thought using and configuring editors didnt require skill

**Comment by tandpfun** [comment]
Added in 47e2fb9bc1353315f589ad5ce992b4f7debf2e48

**Comment by omerfarukdag** [comment]
Thanks, looks great.
