### ISSUE TITLE
[Project Status ⚙️]: Is This Project Still Alive?

### ISSUE THREAD

**Issue by LeleDallas** [tandpfun/skill-icons#539]
Hey @tandpfun, what is the status of this project? Is it still being maintained?

I saw a lot of Issues and PR but the most recent commit was on 2 Feb

**Comment by LeleDallas** [comment]
> Hi Lele,
> 
> We don't accept PRs (as outlined in the readme) as we can't guarantee the quality of SVG exports. Many of the exports we've seen have not worked on some browsers, so all new icons must be created within our master Figma doc (which isn't public at the moment) to guarantee compatibility.
> 
> Due to this, I haven't had time to go through issues and manually redesign/add icons. I've been pretty busy recently! So generally at the moment, the project is somewhat dead.

Thank you for the update and the clarification regarding PRs and the reasons behind it. It's understandable that ensuring compatibility and quality can be a priority for the project. I appreciate your transparency in explaining the current situation.

If there are any changes in the future that allow for contributions or if there are other ways to support the project, please feel free to reach out. In the meantime, I hope things become less busy for you, and the project can progress as needed.

**Comment by Souvik-223** [comment]
I really wish to contribute to this repository as i personally use it. Do you accept PR now.

**Comment by LeleDallas** [comment]
> I really wish to contribute to this repository as i personally use it. Do you accept PR now.

I think no...

**Comment by tandpfun** [comment]
I think automated testing tools is an interesting idea for this, I haven't heard of doing that for SVGs. Would be interesting to explore!

**Comment by irfaan008** [comment]
Like others, I was also impacted by the status of the project and decided to build it again. Here I am ready with 2500+ icons with light, dark & color modes. 

I really respect the work of @tandpfun and that inspired me to build my project in a way, that I don't need to take care of icon creation. This is how I am able to support more than 2500 tech skill icons (and that number will keep growing without me doing anything)

Checkout @LeleDallas @Souvik-223 @jenkin 

https://github.com/irfaan008/simple-skill-icons

**Comment by jenkin** [comment]
@irfaan008 WTF!?! It seems the perfect solution! 😮 Here is my new profile: https://github.com/jenkin

Hmm, I don't know, maybe I preferred the icon background with rounded corners, and some of the new icons doesn't look great on dark bg. And regex is missing!

After
![image](https://github.com/tandpfun/skill-icons/assets/426495/0a6571b8-498d-4d12-bedf-acb1cff52860)

Before
![image](https://github.com/tandpfun/skill-icons/assets/426495/5739bdfd-361c-41ca-88db-f6c78ffa9ba3)

**Comment by LeleDallas** [comment]
> @irfaan008 WTF!?! It seems the perfect solution! 😮 Here is my new profile: https://github.com/jenkin
> 
> Hmm, I don't know, maybe I preferred the icon background with rounded corners, and some of the new icons doesn't look great on dark bg. And regex is missing!
> 
> After ![image](https://user-images.githubusercontent.com/426495/284871945-0a6571b8-498d-4d12-bedf-acb1cff52860.png)
> 
> Before ![image](https://user-images.githubusercontent.com/426495/284871847-5739bdfd-361c-41ca-88db-f6c78ffa9ba3.png)

Yeah, as you said I prefer @tandpfun solution but @irfaan008 project is very cool!
