### ISSUE TITLE
[NEW ICON] [COMPLETED 🥳] Fediverse, Mastodon, Misskey

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#54]
### Skill Name

Fediverse, Mastodon, Misskey

### Why?

Since social icons are starting to be added, it would be a good idea to include the Fediverse. Mastodon and Misskey are by far the two most popular Fediverse services, and the Fediverse logo encompasses the rest of Fediverse servicess (Pixelfed, Pleroma, Hometown, etc)

### Fediverse 
![Fediverse-Light](https://user-images.githubusercontent.com/44733677/159134313-c1390e18-07c1-45ec-843f-449738cde40e.svg)

### Mastodon
![Mastodon-Light](https://user-images.githubusercontent.com/44733677/159134320-23928a21-9185-4192-8e7c-521ebeb71949.svg)

### Misskey
![Misskey-Light](https://user-images.githubusercontent.com/44733677/159134323-1a8c8ffc-1139-46e1-aa23-64808f30a5a3.svg)

**Comment by tandpfun** [comment]
Added all 3 in 79446ce2ce5493d0dfb90d95314f79707155df96. As there is a Cloudflare Workers size limit, I will be paying more attention to the skill-aspect and how many people will likely use the icons. I think the Fediverse icon is a *borderline* skill, and probably won't be super heavily used. I still added it, but I'll be paying more attention to those two things from now on.
