### ISSUE TITLE
[NEW ICON] Skill Name

### ISSUE THREAD

**Issue by zhen1asemen1uk** [tandpfun/skill-icons#541]
### Skill Name

Cypress

### Why?

Popular technology for testing

### Reference Image

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBIREhgSEhIYGBgZGhgYFRgcGBISGBgaGBgZGRoVGhwcIy4lHB4rHxkYJjgmKy8xNTU1GiU7QDs0Py40NTEBDAwMEA8QGhISHjQhJSExNDQ0MTQ0MTE0PzQxNTQ0MTQxNDQxMTQ0MTExNDQ0NDE3NDQ0NDQxNDQxMTQ0NDQ0NP/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAEAAQUBAQAAAAAAAAAAAAAABQEDBAYHCAL/xABEEAACAQICBwQGCAMHBAMAAAABAgADEQQFBhIhMVFhcQcTIkEUMoGCkcFCUmJykqGx0SNzojNDU7LC4fBjk9LxFRYm/8QAGQEBAQEBAQEAAAAAAAAAAAAAAAECAwQF/8QAJREBAQACAQMDBQEBAAAAAAAAAAECEQMSITEEQVEiMmFxkRQT/9oADAMBAAIRAxEAPwDs0REBERAREQEREBERARE+GcDaSB12QPqJhtmVBd9VPxD5Syc7w4/vP6WP6CHO8mE82f1JRI4Z1hz/AHn9L/tLqZlQO6qvtIH6wTkwviz+s2J8K4O0EHobz6h0ViIgIiICIiAiIgIiICIiAiIgIiICIiBSJQzX820kSldKdnbcdvhXqfM8hDGeeOE3anKlQKCWIAG8kgAe2QmM0npJspguePqr8TtPsE1LF4+rWN6jFuA3KOg3CWVk28HL623tjNJnEaQYh9zBRwUW/M7ZHvVZzd2LHiSW/WWVFzYb+EksPk+IfaKZA4tZP12yPJcuXkvvWGs+xJmlozVPrOo6Xb5CZK6Mca39NvnGqs9LzX2QAn0JPnRrhV/p/wB5bfRyoPVdT1DL+8aq/wCXlnsiEYqbqSOhI/SZ2Hzasn07jgfF+e/8581cprp9C44qQfy3zFKkGxBB4EWMeEn/AF477xsOFz1W2OpU8RtH7iS9KsrC6kEcRtmkCXqNZkOsrEHl8x5y7erj9XlO2XdusSGwWcg+Gp4Tx8vbwkwDeV7sOTHOblfUREOhERAREQEREBERAREQKS1WrKilmICgXJOwARXrLTUuxAUC5J3ACc8z7PGxL6q3FNT4V3FvtN8h5Q48vNOOd/LLzvSJqxNOkSqbidzN+w5f+pBKZaBkzkmSPiTreqnm3HkvHru/SR8y3Ply+awsPRZ21UUsx3AC82bLtFSfFXa32F+bft8ZsOAwFOgurTW3E7yeZPnMyNPbxekxx75d6xMJgaVIWRAOdtp6neZlxEr1ySTUViIhSIiBS0s1sOjizKD1AMvykJZL5QeKyIb6Zt9k7R7DvEh62HdDqspB/Xpxm6S1WoK4swBEmnl5PS45d8e1acJIYDMGpbDtThw6ftPrH5Y1PxL4l/MdeXOYAk8PHrLiy+K26hWV1DKbgy7NWwWKak1xu+kOP+82ShWV1DKbgzT6HDzTOfleiIh3IiICIiAiIgUiJrOmGb9xT7pDZ3B2+ar5nqdw9vCGM8pjjbUHpVnnfv3NM/w1PiI+kw8+g8vjwmvAy2DJrRvJziql2uKa2LHdfgo6+fAeyHzMurly/NZujmQnEEVagtTG4bi5H+nnN9poFAVQAALADYAB5CKdMKoVQAAAABsAA8hPuH0eLix45qKxEQ6kREBERAREQEREBERA+bSEzLLrXdBs8x8xyk5EOfJxzOarUAJmZfizTbb6p3j5y5mWC1Drr6p3jgf2mFI+fq8eX5jaw1xcSsicpxP0D5bR8xJUSvo4ZzKbj6iIhsiIgIiIFmtUCKWY2CgkngALkzkmaY9sRWaq30j4R9VRsVfh+d5u2nmYd3hxSU+KobH7q2LfE6o9pnO7w8Pqst2Y/DJwtFqjrTUXZiFA5n5Tq+V4BMNSWmvlvPmSd7GapoDlty2JYbrpT6/Tb9B8ZvMOnpuPpx6r7qxEQ9RETBxua4ah/bYilT++9NP8xgZ0SCGl+Wk2GPw1/wCdS/eSmGxdOqutSqI68UZXHxUwMmIiAiUvKwEREBERAREpA+KqBgQdx2TXK9AoxU+W7mPIzZZH5rQuNYb139DJXDnw6sdzzETTYqQw3jaJsVCoGUMPMTXbSTymrvU9R84jj6fLV18pWJSVle0iIgJSVnw7BQSdwFz7IHLtNcb3uLYA7KYCDqPE3tuSPZIJbk2AuTsA4k7hGJrmpUeod7szn3iT85KaKYXvcZSUjYra59wFh+YWHzLvLP8AddOynBDD0EpD6KgE8TvY+0kzOiIfSk1NEgdJ9J8NllLXrtdmv3dNbF3I4DyA2XY7BfoJf0mzunl+FfE1NoUWRRvdjsVB1Pn5C58p5xznNa2MrtiK76zsfdRfoog8lHkOpO0kzWOO1T2kXaBj8aSBUNCmd1OkzKbfbcWZj0sOU1O20nzO0nzJ4k+cTdMi7NcwxSioyrQQ7VNTWDkeRCLtHvapm+0Rpc+8PVem4qU3ZHG50ZkcdGUgidOfscrW2Y5CeBouB8dc/pNT0i0Ix2XqXq0w9Mb6tMl0A4uCAy9SLc46oJ7RjtRxVBhTxn8enuL2C1kHHZYOORseflOxZXmNHFUlrUHDowurD8wRvDDcQdoM8tTaNBNK3y3EXYk4dyBXTabeQqqPrL523jZt2Wzlj8G0l2vZEtDHDEKo1MQusdm6ollf4goepaaF3S/VHwE9D9o+UDHZa5SzPTAr0iLNragJIHHWQsBzInnsGXHvCu99k2cek5etJj48Oe6PNAL026ap1eqGbxOAdlOc+i5itNjZMQO6bhr+tTb43X356AmMpqkIiJFaJ2tZz6Nl5oqfHiD3Y+5a9Q9NXw++JwPuk+qPgJu/apnHpWYsim6Ycd0vDXveo34rL7k0xVLEKoJJICgbySbADmTYTpjNRHT+xTIgalXHMgAUdzSNreJgGqMOg1Vv9pp2F1BBB3HYZEaKZOMDg6WGFrqt3I+k7eJz+In2WkzMW7o1x01SVPkSJcwr6rqedj0OyX8xSz34gH5TFtMvBZ05/psUrLNFtZQeIEuyvfLtWJSVhVJG6Q1u7wldhvFN7dSpA/MySkDpq+rgKx5KPi6j5wzldY1ya82/s4o62IqP9Wnq/iYf+BmmXm/dmI2Yhv5Y+HeH5yvDwz6436IiR9BxDtlzk1MWmEU+GiodhxqOL7eiatvvmc6k3pniO8zLFOf8Z1/AdQfkgkKlMuQi72IUdWNh+s6yaiOs9k2h6FFzHEJckn0ZTtCgGxrEfWJBC8Bt8xbrUxsDhVo0kpILKiKijgFUKB8BMmc7dqS26Aggi4IsQdoI4S5Eg4J2maILgKyVcOhFGs2qqAE93U2nUUfVYAkDysw3Wkdk+gOZ4qxXDmmh+nWPdD8JBc/hnokqPMbton1Ndd0mkJoplVTB4Onhq1UVWQFQwUqNW51UsSdijw34ATgemeTegY6rQAsmtr0v5b3Kgch4l9yel5zDtoyXvKFPGoPFSOpU503PhJ6PYe+YxvcrjqOykMhsykMrDeGU3Vh0IBnpzRrNlxuEpYlf7xAWH1XHhdfYwYeyeYZ1nsVzr+2wLn/rUumxaij26je8ZrKdiOtSK0mzZcFg62JNrohKg/Sc+FF9rFRJacj7a85/scEh/wCtVHxWmp5eufdExJuq5SzsxLMdZiSWY72JNyx5kkmbj2WZL6VmCuwumHHetwL7qa/iu3uTTJ3zsoyX0XL1qOLPiD3rcQhFqa/h8XVzN5XUSN4iInNUdma7Aeo/58JH2kpmPqjr8jI20lePmn1JXAeoOVx+cyZiZf6vt+QmXK9OH2wiIhsmv6cLfL63RD8Kin5TYJE6T0tfBV1H+E5HuqW+UM5TeNjjF5v/AGXtsxA4GmfiH/ac9vN17MK9q9Wn9amrfge3+uarx8XbOOmRETL3PMel1Du8xxSH/Hqt+Ny4/JhImnV7tle19UhrcdUg2/Kb52wZSaOPGIA8GIQG/l3lMBHH4RTPx4TQZ1neI9XUKq1EV1N1YBlPEEXB+Bl6c17JdK1rUFwFVgKtIWpXPr0xuUfaQbLfVAPG3Spzs0pERIKROOdp+mjmumFwdZk7ltarURyl6gBAphlPiCgtrDdfZ9EyLyjtUzChYVgmIUfWHdP+JRb4qZrpuk27xMHNsAmKoVMPU9WojIeI1gRccxvHMTF0azkY/DJiVpNTD3sr2vYEjWFt6m2w+YkxMq8pY3CPQqvRqCzo7I/VSQSORtccjMzRrNjgcXRxW2yONfftRgVcc/CT7QJuXbHkvc4tMWo8NddV+VRABf3k1fwGc6nWXcR6v71dXXuNW2te+zVtfWvwtPMekubHHYurijezuSgN9lNfDTHLwgX5kzdv/uH/AOd7gN/G1vQ/O4p6utrdO68N+M5tJjNCV0Yyg47GUcMBsdxrngi+Jzy8IIHMiem6aBQFAAAAAA2AAbAJyvsUyWyVccw9Y9zSP2VIaow5FtVfcM6vM5XuRWIiZViZh6vt+RkbaSGPOwDnf/nxmHaR5eX7mbl/qnr8hMuY+DFlEyJXfD7YREQ2rLdamGVlO5gQehFpclIHn+tTNN2ptvRip6qSD+km9CMZ3WPpEnY+tTPvjw/1BY06wXc46ps8L2qL748X9YeQFOqyMHQ2ZSGU8CpuD8QJp4ddOf6r0LEw8sxi4iilZdzqGHK42jqDceyZky9zX9MtHVzHCNQJCuPHRc7dV1vYn7JBKnkxnnLHYOpQqPRqqVdGKup3gj9QRYg+YIM9WTU9MtCqGZprH+HXUWSqBfZvCVB9JfzF9h2m+sctDz3SqMjB0YqykFWUlWUjcQRtB5zouRdrOJpKExdJa4GzXU91U94WKsemrNQz/RnGZexGJpEL5VFu9JuYa2zo1jykNN6lR2Zu2HC22YTEX4E0QPjrH9JqekfabjMWrU6SjDIbg6rF6jDgX2ao+6Aec0WCQN8kxibJOaIaN1MyxK0UuEFmruPoJfyP1msQo6ncDJLRjs/xmOKsyGhR86jqVYj7CGxY8zYczunb9H8iw+X0RRw6ao3sTtZ283c+Z/IbhYRllpdJDC4dKSLSpqFRFVEUblVRYKOgAl+InNWsdoGSenZfVpqLuo7ylxLpt1R94ay+9POSm4vPWc84doGS+hZhVRRZHPe0uGpUJJA6PrrbgBN4X2Stbn3QovUdadMXd2VEHFnIVV9pIE+JvvZDkvpGOOIYXTDrrDgaj3VfgA56hZu3Q7LkOVpg8LSwybqaBb8W3s3UsSfbJKInFSIlCYGBjGu1uA/WY9pdc3JPGKa3YDnI8uX1ZM6itlA5S5ESvTJoiViFIiIGidp+W69BMSo2021W+65AB9jW/EZy+89BY3DJWpvScXV1KsOTC04JmeCfDVnoP6yMVPMb1YciCD7ZqPNzY99uh9mGb61N8I52pd6fNWPiUdGN/f5ToE8+ZXmD4asldPWQ3tuDDcynkRce2d3y3HpiKSVqZurrccRxU8wbg9JLHTiy3NfDNiIkdXw6gixAIO8HaDNexuhGWViS+CpAk3JUGibnzJQi5myRA01ezPKQb+jE8jVxFv8ANJnLNGMBhSGoYSkjDc+qrP8Aja7fnJiI3RWIiAiIgUnDe2TM1rY1KCgfwEIdvPXqar6nQKEPVzOy5tj0w1CpiKnq00Z25hRew5nd7Z5gx2LevVes5u7uzv57XJJA5C9h0msJ32lWCZ6G7Ncl9Dy6mGFnq/xqmyxBcDVU8woUdQZxbQrJvTsfSoMLpfXq8O7SxYHkx1V9+elpc77EViImFUlnEPYW4y8TMKo2sbwzldRbtL+ETaW9ktWmbTSwtDnhj32+4iIdiIiAiIgUmgdpeQGogxdMeKmLVQN7J5N1Uk+wnhOgS26gixAIOwg7QRwhnLHc084kzbtAtKBhKnc1mtRqH1jupudmtyU7AeGw8Zjab6NHA1dZAe4ckofqHeaR6eXEdDNWJmvLzzeGT0oJWcs0C01CauExTWTYtGoT6vCm5+rwPluOzd1OSx6McpYrERI0REQEREBEShMDmHbTnWpQp4JTtqsKlQcKaG6g9XAPuGcbk3pjnPp2Oq4gG6FtSlw7tPCpHI7W98yMy/BviKqUKY8dR1RPPaxtc8hvPIGdZNRHXuxjJdTDvjHHiqtqJ/LpkgkdX1vwCdOmFleBTDUadCmLLTRUXjZQBt5nfMyc7d1VZSJbdvISJbp81WvsHtlgiXCIVLyOd71Wgnn8JkSkrK6SaisREKREQEREBERAwszwFPFUmo1V1lcWI8xwIPkQdoM4dpTo7Vy+rqPdka/dVLbGHA8HHmPbunfZhZnltLFUmo1kDI28biCNxB8iOIll0xlj1POZm6aH6ePhNWhitZ6O5W9Z6Y4fbQcN48r7BI7S3RCtl7Fxd6BPhqAbVvuVwPVPPceW6auTNeXKbxr0rgcbSroKlJ1dG9VlNwf2PKZM84ZPnmJwVTvMPUK39ZT4kf767j13jyInTsg7TsNVsmKU0G+uLvSPt3r7RbnM3Gu0yldCiWMNiEqKHpurqdzKQynoRsl+RoiIgUmn9p2deiZfUCtZ638FLbCNcHWYcLIG28bTcZwXtbzr0nH9wpumHXU5Go1mc+zwL1Uy4zdGizo/Y1kve4p8W48NBdRP5jggkfdS/wD3BOcEz0hoJkvoOApUWFnI7yr/ADH8RHuiy9FE3ldRI2SIlDOavktLREuGUC3hm93wFvLyraFFp9QsmiIiFIiICIiAiIgIiICIiBaqU1dSrKGUggggEEHeCDvE5vpR2ahiauAIU7zRY2U/cb6P3Ts5idNlJZdJZL5eZMdhKtCoadamyON6sCp6jiOY2GYxM9K5plOHxaamIpK6+WsNq81YbVPMGc8zvsoBu2Dr24U6tyOgdRcDqCec1MoxcbPDmeBzGthm16FV6beZRmS/3gNjDkbzbMv7UMxpWFTu6w+0ndufeQgf0yDzbRXH4QnvcK+r9dF71LDz1kvqj71pAky6lJuOsYXtgS38bBMD9ioj39jBbfEySp9reXn1qWIXqlI/5XM4mZ8GOmNbrtGZdrmDWm3o9Ks9Sx1QyoiX8ix1ibdAZxepVZ2Z3YszMzOx3szEszHqSTPmXcPh3qutOmjO7GyIoLMx4ASySK2Ls7yX0zMaSMt0pnvqnCyEFF9r6gtw1p6Nmndnmif/AMbhz3hBr1bNVI2hQB4aSnzC3Nz5knytNwnPK7qqyhlYkFLRKxAREQEREBERAREQEREBERAREQEREBERASNx+R4TE/2+GpVObU0Y/Ei8kogadiezbKqhv6OyH7FWuo/Drao+Ej6vZLlzbnxC9KiH/MhnQIl3U059S7JMuU3L4huRqIB/SgP5zacj0aweAFsNQVCd7bWc8i7EsRyvaTMpJbaqsREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQEREBERAREQERED//2Q==

**Comment by tandpfun** [comment]
Added in e67133b!
