### ISSUE TITLE
[NEW ICON] Heroku

### ISSUE THREAD

**Issue by merive** [tandpfun/skill-icons#55]
### Skill Name

Heroku

### Why?

Heroku is one of the most popular cloud platforms.

### Reference Image

![heroku-logo-solid-purple](https://user-images.githubusercontent.com/52623720/159158579-a04b4b27-79eb-4d51-8adb-430fdd8ebfc6.svg)

**Comment by tandpfun** [comment]
Added in 79446ce2ce5493d0dfb90d95314f79707155df96
