### ISSUE TITLE
[NEW ICON] Skill Name

### ISSUE THREAD

**Issue by CHRNVpy** [tandpfun/skill-icons#556]
### Skill Name

MongoDB

### Why?

It's popular

**Comment by k-haruaki** [comment]
there is already
https://github.com/tandpfun/skill-icons/blob/main/icons/MongoDB.svg
![Screenshot 2023-09-19 at 23 24 19](https://github.com/tandpfun/skill-icons/assets/65454615/6a1aba60-744f-4547-bd07-7617cba53191)

**Comment by CHRNVpy** [comment]
Oh, sorry, my eyes were wide closed then))

**Comment by k-haruaki** [comment]
I'm happy to be of help to you👍

**Comment by k-haruaki** [comment]
I would be happy if you could close the Issue!!
