### ISSUE TITLE
[REPORT] Plan9 icon outdated

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#56]
### The issue

The Plan9 icon uses the old Glenda SVG I made, but I made a better one recently: https://gist.github.com/ThatOneCalculator/a71d17c38cd1a96697ed6b0e782a5705

**Comment by tandpfun** [comment]
Fixed in 79446ce2ce5493d0dfb90d95314f79707155df96, thank you!
