### ISSUE TITLE
[NEW ICON] Visual Studio

### ISSUE THREAD

**Issue by Yoroion** [tandpfun/skill-icons#57]
### Skill Name

Visual Studio

### Why?

There is an icon for vscode in the list, then I consider that it will be better with an icon for Visual Studio. Visual Studio is still one of the most powerful IDEs for .NET

### Reference Image

![Product-Icon](https://user-images.githubusercontent.com/59552671/159238394-a4f8e840-a644-4c4a-8ff9-56d278e5a1b8.svg)

**Comment by tandpfun** [comment]
Added in 79446ce2ce5493d0dfb90d95314f79707155df96 as `visualstudio`
