### ISSUE TITLE
[NEW ICON] Light theme for Remix icon

### ISSUE THREAD

**Issue by arpitdalal** [tandpfun/skill-icons#58]
### Skill Name

Remix

### Why?

I know there already is an icon for Remix, but there is no light version because the proposer thought [Remix didn't like their brand colors changed](https://github.com/tandpfun/skill-icons/pull/5#issuecomment-1065369983) but Remix team has already made their logos folder public and in there, there are light logos of Remix, so I think a light version can be added. Here's the [google drive folder of remix logos](https://drive.google.com/drive/u/0/folders/1pbHnJqg8Y1ATs0Oi8gARH7wccJGv4I2c) made public by their team.

### Reference Image

https://drive.google.com/drive/u/0/folders/1pbHnJqg8Y1ATs0Oi8gARH7wccJGv4I2c

**Comment by tandpfun** [comment]
Fixed in 79446ce2ce5493d0dfb90d95314f79707155df96. Thank you!
