### ISSUE TITLE
[NEW ICON] OpenStack

### ISSUE THREAD

**Issue by haydenwalker980** [tandpfun/skill-icons#59]
### Skill Name

OpenStack

### Why?

Popular private cloud service many organizations and individuals (myself included) use for things like testing code. Similar to OpenShift.

### Reference Image

SVG, w/ wordmark: https://upload.wikimedia.org/wikipedia/commons/e/e6/OpenStack%C2%AE_Logo_2016.svg  
Without wordmark: https://avatars.githubusercontent.com/u/324574?s=280&v=4

**Comment by tandpfun** [comment]
Added in 9e1ef97!
