### ISSUE TITLE
New fork + improvement 🚀

### ISSUE THREAD

**Issue by Neurs12** [tandpfun/skill-icons#592]
I've been using it for quite a while now (1 year to be exact) and I like it.

However, the author seems to abandoned this project without even considering pulling any requests. So I'm here to happily announce that I've forked this project and continue the development of "skill-icons" under the name "sili-icons", all contributions are welcomed.

I've made some changes to the whole project, and brushed everything up, making it easier to add new icons without the terror of a massive folder full of unorganized svg files as well as clean up the code and reduce load time.

Check it out: https://github.com/Neurs12/sili-icons
@tandpfun

**Comment by tandpfun** [comment]
Love the organization improvements. 

> without even considering pulling any requests
I can't accept PRs for inconsistencies with SVGs. All PRs I've reviewed (when they were accepted) have had small issues with exporting (ie not being created in Figma, or not supporting all platforms) or didn't follow icon guidelines correctly. Information on this is clearly outlined in the readme.

It's true that I've been inactive on the project, I've been really busy these past few months and haven't had much of a chance to work on anything, let alone this on the side. Appreciate your concern and dedication to the icons.

(I will be closing this, as it isn't an issue, but won't delete it)

**Comment by Neurs12** [comment]
Well I don't want to judge you or anything. Just wanted to keep the spirit of the project alive. Lots of people asking for new icons and pull requests for a long time now, and still do to this day, I just can't do nothing about it 😗.


Anyways, no pressure on you at all, stay safe!
