### ISSUE TITLE
[NEW ICON] Discord

### ISSUE THREAD

**Issue by callumisdumb** [tandpfun/skill-icons#6]
**Skill Name**
Discord

**Why?**
Popular chat platform, would be good to add into 'social' parts of GH readmes

**Reference Images (optional)**
[Ref](https://www.svgrepo.com/show/353655/discord-icon.svg)

**Comment by ThatOneCalculator** [comment]
These are *skill* icons. Discord isn't a skill (unlike Discord bot programming).

**Comment by callumisdumb** [comment]
> These are _skill_ icons. Discord isn't a skill (unlike Discord bot programming).

Could use it for stuff like Discord Bots, would be fairly useful either way.

**Comment by ThatOneCalculator** [comment]
> Could use it for stuff like Discord Bots, would be fairly useful either way.

Discord bots has a different logo than Discord.

https://discord.com/assets/245b7cb607ba382289c23aa668786c28.svg

**Comment by callumisdumb** [comment]
> > Could use it for stuff like Discord Bots, would be fairly useful either way.
> 
> Discord bots has a different logo than Discord.
> 
> ![](https://camo.githubusercontent.com/bdb1201c93209860cf002a85a608dbc7e462d05a235041c3e338cfdf8215b194/68747470733a2f2f646973636f72642e636f6d2f6173736574732f32343562376362363037626133383232383963323361613636383738366332382e737667)

That logo doesn't really represent any meaning, it'd be better to have a Discord logo or a mix of the two to give the icon some meaning.

**Comment by ThatOneCalculator** [comment]
> That logo doesn't really represent any meaning, it'd be better to have a Discord logo or a mix of the two to give the icon some meaning.

What do you mean? That's literally the official icon Discord uses for bot development.

**Comment by ThatOneCalculator** [comment]
On that note, for Discord brand colors, this could possibly work:

![DiscordBot](https://user-images.githubusercontent.com/44733677/157930083-dc898527-e1d5-49a4-bf86-b5d4e2699663.svg)

**Comment by ThatOneCalculator** [comment]
Fixed it being off-center:
![DiscordBot](https://user-images.githubusercontent.com/44733677/157930786-31c1e31c-902e-4e7e-9602-ecfc42205d36.svg)

**Comment by callumisdumb** [comment]
> Fixed it being off-center: ![DiscordBot](https://user-images.githubusercontent.com/44733677/157930786-31c1e31c-902e-4e7e-9602-ecfc42205d36.svg)

Looks good, you should make a PR for this and I can just close this issue so it's not flooding the issues board

**Comment by ThatOneCalculator** [comment]
Fixed by #5

**Comment by tandpfun** [comment]
Let's not PR that for now, I'll explain why when I'm free in a bit

**Comment by ThatOneCalculator** [comment]
Gotcha. I'll revert

**Comment by callumisdumb** [comment]
> Let's not PR that for now, I'll explain why when I'm free in a bit

Fair enough 👍

**Comment by tandpfun** [comment]
Added Discord and Discord Bots logo in 28fb8ab
