### ISSUE TITLE
[NEW ICON] Terraform 

### ISSUE THREAD

**Issue by Mr-Saikiran** [tandpfun/skill-icons#612]
### Skill Name

Terraform

### Why?

**Popular for infrastructure provisioning**

### Reference Image

![terraform-original](https://github.com/tandpfun/skill-icons/assets/20139599/cff44b53-6d5e-43f6-8b6d-5bed27a2ffab)
![terraform-plain](https://github.com/tandpfun/skill-icons/assets/20139599/1894c97f-aa02-4ffb-b8b1-95f6d58651a5)

**Comment by irfaan008** [comment]
Use this library as it supports 2500+ icons @Mr-Saikiran 

https://github.com/irfaan008/simple-skill-icons

**Comment by alirezanqp** [comment]
up
