### ISSUE TITLE
[NEW ICON] Cypress

### ISSUE THREAD

**Issue by jojosuelobo** [tandpfun/skill-icons#615]
### Feature requested

Cypress

**Comment by irfaan008** [comment]
@jojosuelobo Use this library as it supports 2500+ icons

https://github.com/irfaan008/simple-skill-icons

**Comment by jojosuelobo** [comment]
> @jojosuelobo Use this library as it supports 2500+ icons
> 
> https://github.com/irfaan008/simple-skill-icons

Used on Cypress icon, thx man

**Comment by tandpfun** [comment]
Added in e67133b!
