### ISSUE TITLE
[NEW ICON] Pinia

### ISSUE THREAD

**Issue by Grayvox** [tandpfun/skill-icons#626]
### Skill Name

Pinia

### Why?

Pinia is a state management tool for the Vue.js ecosystem. I myself am a big fan of it and it's popular enough I think it should be added for users to display on their profiles.

### Reference Image

<img src="https://github.com/tandpfun/skill-icons/assets/144566632/ffbfe2ee-6349-4015-b411-81914d18a1e7" height="300" width="auto">

**Comment by tandpfun** [comment]
Added in e67133b!
