### ISSUE TITLE
[NEW ICON] PowerShell

### ISSUE THREAD

**Issue by skepfusky** [tandpfun/skill-icons#63]
### Skill Name

PowerShell

### Why?

Similar to Bash, PowerShell is simple, yet powerful scripting language from Microsoft primarily for automation of tedious and repetitive tasks to run, build, and test systems and servers via the .NET ecosystem.

### Reference Image

![](https://upload.wikimedia.org/wikipedia/commons/2/2f/PowerShell_5.0_icon.png)

**Comment by tandpfun** [comment]
Added in 9e1ef97!
