### ISSUE TITLE
[NEW ICON] Amazon DynamoDB

### ISSUE THREAD

**Issue by urienix** [tandpfun/skill-icons#65]
### Skill Name

DynamoDB

### Why?

Because it is very popular among developers who use AWS services

### Reference Image

![dynamo](https://user-images.githubusercontent.com/20466553/160706737-31d36794-9318-424a-bb5e-d50a43f3f381.png)

**Comment by ThatOneCalculator** [comment]
I think this might already be covered (sorta) by the existing AWS badge

**Comment by tandpfun** [comment]
Added in a50fa57465e82a1147fa512fb3d64cc5902df578
