### ISSUE TITLE
[NEW ICON] PyTorch, Bevy

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#66]
### Skill Name

PyTorch, Bevy

### Why?

PyTorch: Very popular ML framework
Bevy: Very popular Rust game engine

### PyTorch
![pytorch](https://user-images.githubusercontent.com/44733677/160755991-b6ed3a8e-3847-445a-9c33-e712f4026f1a.svg)

### Bevy
![bevy_logo_dark](https://user-images.githubusercontent.com/44733677/160755889-1238cf1e-9b91-47c9-9901-2886c3a0a4d4.svg)

**Comment by tandpfun** [comment]
Added in a50fa57465e82a1147fa512fb3d64cc5902df578
