### ISSUE TITLE
[NEW ICON] Unity Icon

### ISSUE THREAD

**Issue by paolo-05** [tandpfun/skill-icons#665]
### Skill Name

Unity Engine Icon

### Why?

It's one of the most used game engines out there, especially by indie developers. 

### Reference Image

<img src="https://cdn.sanity.io/images/fuvbjjlp/production/36cbc8ae92c7711afb9ab1ec9f7174863f4d7c19-22x24.svg"/>

**Comment by TheLime1** [comment]
![image](https://github.com/tandpfun/skill-icons/assets/47940043/b2e890b9-f9d8-43da-bfc6-6b74bf175f7d)
