### ISSUE TITLE
[NEW ICON] Pygame, SvelteKit, AlpineJS, Netlify, Heroku

### ISSUE THREAD

**Issue by SuPythony** [tandpfun/skill-icons#69]
### Skill Name

Pygame, SvelteKit, AlpineJS, Netlify, Heroku

### Why?

Pygame; Very popular python game library
SvelteKit - Popular meta framework for svelte
AlpineJS - Another frontend framework
Netlify and Heroku - Popular hosting services

### Reference Image

Pygame:
![large](https://user-images.githubusercontent.com/67601246/161041171-6f376073-0be9-41e6-ba7c-dc39ee8c8356.png)

SvelteKit:
![image2vector](https://user-images.githubusercontent.com/67601246/161040703-e4685e0d-50a2-4477-a5e5-738e00a207e0.svg)

AlpineJS:
![mediamodifier_cropped_image](https://user-images.githubusercontent.com/67601246/161040171-6d774645-de1c-4a8e-be8c-c64b35b4e1e8.png)

Netlify:
![logomark](https://user-images.githubusercontent.com/67601246/161038211-25d101a5-85ec-433d-9dc4-6444c978d1ff.svg)

Heroku:
![heroku-logo-stroke-gradient](https://user-images.githubusercontent.com/67601246/161038807-3f367e42-d058-458f-bc89-e54b70b350fd.svg)

**Comment by skepfusky** [comment]
@SuPythony These icon requests are alright, but SvelteKit might be a duplicate, as both Svelte and SvelteKit has the same logo minus the text.

**Comment by SuPythony** [comment]
@skepfusky Yeah, that's a problem. But Svelte and SvelteKit are different skills, so I believe they should have different icons too.

**Comment by skepfusky** [comment]
@SuPythony Ah, I can see why. But I guess it'll be placed under a different background color perhaps? I'm not sure :p

**Comment by SuPythony** [comment]
@skepfusky The Svelte icon in this repo is not the original one but with inverted colors. So I think we can use the original Svelte logo for SvelteKit. Also, the text would be necessary like only SK can be written to differentiate it from Svelte.

**Comment by tandpfun** [comment]
Heroku already exists, I'll work on adding the other ones when I'm less busy next week.

**Comment by SuPythony** [comment]
@tandpfun Heroku isn't there in the readme list

**Comment by tandpfun** [comment]
I can't find a pygame logo, I think svelte & sveltekit are branded in the same way, so the svelte icon covers that.

**Comment by tandpfun** [comment]
Added in a50fa57465e82a1147fa512fb3d64cc5902df578
