### ISSUE TITLE
[NEW ICON] Flask

### ISSUE THREAD

**Issue by skepfusky** [tandpfun/skill-icons#70]
### Skill Name

Flask

### Why?

Since [Oxicode](https://github.com/Oxicode) requested Django (#64) -- I'd be fitting to also add an equally popular Python web framework, but it's lightweight and fast

### Reference Image

![](https://upload.wikimedia.org/wikipedia/commons/3/3c/Flask_logo.svg)

**Comment by tandpfun** [comment]
Added in a50fa57465e82a1147fa512fb3d64cc5902df578
