### ISSUE TITLE
[NEW ICON] Github

### ISSUE THREAD

**Issue by UltraLionfr** [tandpfun/skill-icons#71]
### Skill Name

Github

### Why?

Add the github icon to decorate our profile a bit more

### Reference Image

![GitHub-Mark-120px-plus](https://user-images.githubusercontent.com/49597041/161446806-cd188150-fac9-487d-875e-8e3b1d652015.png)

**Comment by tandpfun** [comment]
Added in a50fa57465e82a1147fa512fb3d64cc5902df578
