### ISSUE TITLE
[NEW ICON] JetBrains Rider

### ISSUE THREAD

**Issue by Polarzincomfrio** [tandpfun/skill-icons#721]
### Skill Name

JetBrains Rider

### Why?

It's very popular amongst C++/UnrealEngine developers

### Reference Image

![JetBrains_Rider_Icon](https://github.com/tandpfun/skill-icons/assets/69534455/f51f9b9b-ffa8-4a67-8b54-f0645a7e828f)

**Comment by ayrudev** [comment]
closing since it has been added
