### ISSUE TITLE
[NEW ICON] Neovim

### ISSUE THREAD

**Issue by fky2015** [tandpfun/skill-icons#74]
### Skill Name

Neovim

### Why?

Neovim is a Vim-based text editor that seeks to aggressively refactor Vim in order to provide modern editing and programming experience.

Neovim hit 50k stars on the Github and became the most popular collaboration tool [in the StackOverflow's 2021 developer survey](https://insights.stackoverflow.com/survey/2021#most-popular-technologies-new-collab-tools).

I've noticed that the Vim icon is in the list. But since Vim and Neovim are often considered two different text editors, and skills in two editors are not fully equal, I suggest we add the Neovim icon into this project.

### Reference Image

https://www.vectorlogo.zone/logos/neovimio/index.html

![](https://www.vectorlogo.zone/logos/neovimio/neovimio-icon.svg)

**Comment by tandpfun** [comment]
Added in 9904dfdfef9bf5d8ae649a85fcb531b5892b0796!
