### ISSUE TITLE
[NEW ICON] D, NumPy, Matplotlib, more...

### ISSUE THREAD

**Issue by Kaamkiya** [tandpfun/skill-icons#756]
### Skill Name

D, NumPy, Matplotlib, CodeSandbox

### Why?

* [D](https://dlang.org/) is a widely used coding language, and I'm sure there are people who would like to put it on their READMEs (including me). 
* [Numpy](https://numpy.org/) is a *very* widely used Python library for data science, which tons of people (again, including me,) would love to have on their READMEs. 
* [Matplotlib](https://matplotlib.org/) is one of the most widely used Python chart-making libraries. 
* [CodeSandbox](https://codesandbox.io/) is an online sandbox that many people use when testing ideas or to show projects. It'd be nice to see this.
* [Erlang](https://erlang.org) is another coding language that's fairly popular, and would be nice to be able to put on profiles.
* [Glitch](https://glitch.me) is another platform where people can build websites for free. It would be awesome to be able to show off my Glitch profile from my README.

### Reference Image

<img src="https://simpleicons.org/icons/d.svg" title="D icon" alt="D icon" width="50px">

**Comment by josemateuss** [comment]
@Kaamkiya D lang was megered in https://github.com/LelouchFR/skill-icons/pull/94, please take a look in https://github.com/LelouchFR/skill-icons and migrate to this new repo.

**Comment by Kaamkiya** [comment]
Thanks, I'll migrate when I get a chance :)
