### ISSUE TITLE
[NEW ICON] [COMPLETED] Hare

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#77]
### Skill Name

Hare

### Why?

New programming language that's quickly gaining popularity

### Reference Image

![Hare-Light](https://user-images.githubusercontent.com/44733677/165230331-95086d78-e0b4-4d14-abb4-7b78bad6a730.svg)
![Hare-Dark](https://user-images.githubusercontent.com/44733677/165230338-1871a5b6-a2ac-448e-b43a-299e4bbd7cbb.svg)

**Comment by tandpfun** [comment]
I don't think this one is widely used enough

**Comment by ThatOneCalculator** [comment]
> I don't think this one is widely used enough

Hare is new but it's getting tons of users
