### ISSUE TITLE
[NEW ICON] Symfony

### ISSUE THREAD

**Issue by Zeryther** [tandpfun/skill-icons#78]
### Skill Name

Symfony

### Why?

Symfony is a highly popular framework to create scalable applications with PHP.

### Reference Image

![143937](https://user-images.githubusercontent.com/5731334/165281052-cd6755ce-0627-4551-8545-542db4bf9329.png)

**Comment by tandpfun** [comment]
Added in 9904dfdfef9bf5d8ae649a85fcb531b5892b0796!
