### ISSUE TITLE
[NEW ICON] Elysia

### ISSUE THREAD

**Issue by Aryxst** [tandpfun/skill-icons#784]
### Skill Name

Elysia

### Why?

[Elysia](https://elysiajs.com/) uses typescript with End-to-End Type Safety, unified type system and outstanding developer experience. It is powered by the emerging tool [Bun](https://bun.sh/) with [uWebSockets ](https://github.com/uNetworking/uWebSockets] and reaches incredibly low response lantency.
 I think that bun will grow up to be big and sow will Elysia in the future.

### Reference Image

![Elysia](https://elysiajs.com/assets/elysia.svg)

**Comment by tandpfun** [comment]
Added in e67133b!
