### ISSUE TITLE
[NEW ICON] Discord.js

### ISSUE THREAD

**Issue by Aryxst** [tandpfun/skill-icons#785]
### Skill Name

Discord.js

### Why?

It's basically the only framework to build discord bots with javascript, and its great.

### Reference Image

![Discord js](https://github.com/tandpfun/skill-icons/assets/101392520/1af1e334-3e9f-4fe1-81e1-621bd6a472d8)
![Discord js](https://discord.js.org/logo.svg)

**Comment by exefer** [comment]
There's also sapphire, but djs is an og

**Comment by LelouchFR** [comment]
> There's also saphhire, but djs is an og

If you want us to implement another icon, please make a new issue, so it is easier to maintain, thank you.

**Comment by tandpfun** [comment]
Added in e67133b!
