### ISSUE TITLE
[NEW ICON] SurrealDB

### ISSUE THREAD

**Issue by ASoldo** [tandpfun/skill-icons#787]
### Skill Name

surrealdb

### Why?

Very popular and fast growing db written in rust.

### Reference Image

![surrealdb](https://github.com/tandpfun/skill-icons/assets/1175537/49a71062-567a-4369-a916-8c1256a57f4f)

**Comment by LelouchFR** [comment]
added to the new project https://github.com/lelouchfr/skill-icons

**Comment by ASoldo** [comment]
For this url we get 404. Even on https://github.com/lelouchfr/skill-icons?tab=readme-ov-file image is missing.

https://github.com/LelouchFR/skill-icons/blob/main/assets/surrealDB-dark.svg

**Comment by LelouchFR** [comment]
@ASoldo Yeah right mb, maybe open an issue on it so I fix it

**Comment by LelouchFR** [comment]
> For this url we get 404. Even on https://github.com/lelouchfr/skill-icons?tab=readme-ov-file image is missing.
> 
> 
> 
> https://github.com/LelouchFR/skill-icons/blob/main/assets/surrealDB-dark.svg 

The link works, read the doc, there is actually just a problem with the readme https://go-skill-icons.vercel.app/api/icons?i=surrealdb

**Comment by ASoldo** [comment]
![image](https://github.com/tandpfun/skill-icons/assets/1175537/48f4dbe8-c208-47ab-9b90-5414b972a3e0)
![image](https://github.com/tandpfun/skill-icons/assets/1175537/885cb3e4-5632-4b14-bffd-174e8e33c021)

for me it's not working.

**Comment by ASoldo** [comment]
I had to use new url https://go-skill-icons.vercel.app/api/  instead of what i had before https://skillicons.dev/icons?i=. Now its working!

**Comment by LelouchFR** [comment]
notice, it's another project, so have fun asking other icons to add there and not here ;)

**Comment by ASoldo** [comment]
i don't care anymore
