### ISSUE TITLE
[NEW ICON] PyCharm

### ISSUE THREAD

**Issue by Yeikzy** [tandpfun/skill-icons#79]
### Skill Name

PyCharm

### Why?

PyCharm is a code editor for Python created by the JetBrains team, I think it can be interesting for Python developers to add one of the most used IDEs.

### Reference Image

https://resources.jetbrains.com/storage/products/pycharm/img/meta/pycharm_logo_300x300.png

**Comment by tandpfun** [comment]
Appreciate the suggestion! IDEs aren't super skill-y so we're probably not going to add more for now.
