### ISSUE TITLE
[NEW ICON] PhpStorm and WebStorm

### ISSUE THREAD

**Issue by skepfusky** [tandpfun/skill-icons#80]
### Skill Name

PhpStorm and WebStorm

### Why?

PyCharm was requested at #79, so I decided to request some few IDEs from JetBrains

PhpStorm and WebStorm is an IDE specifically for PHP and JavaScript respectively

### Reference Image

![](https://upload.wikimedia.org/wikipedia/commons/c/c9/PhpStorm_Icon.svg)
![](https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/WebStorm_Icon.png/1024px-WebStorm_Icon.png)

**Comment by tandpfun** [comment]
Appreciate the suggestion! IDEs aren't super skill-y so we're probably not going to add more for now.
