### ISSUE TITLE
[NEW ICON] Prometheus

### ISSUE THREAD

**Issue by VictorGrycuk** [tandpfun/skill-icons#809]
### Skill Name

Prometheus

### Why?

[Prometheus](https://prometheus.io/) is a well known monitoring system & time series database

### Reference Image

![Prometheus_software_logo svg](https://github.com/tandpfun/skill-icons/assets/39467613/fc562e0a-c80f-4894-b675-225ffb1f76b6)

**Comment by LelouchFR** [comment]
it's already in the project, please look correctly the whole list if you want to do an icon sugggestion.

![image](https://github.com/tandpfun/skill-icons/assets/75901978/6cee9289-76db-4eb4-a13e-99735303a4f4)

if you want to use it, do:

```md
[![My Skills](https://skillicons.dev/icons?i=prometheus)](https://skillicons.dev)
```

which gives:

[![My Skills](https://skillicons.dev/icons?i=prometheus)](https://skillicons.dev)

**Comment by VictorGrycuk** [comment]
Oh wow, somehow I missed it. Sorry about that.

**Comment by LelouchFR** [comment]
No problem ;) Here to help
