### ISSUE TITLE
[NEW ICON] SQLite

### ISSUE THREAD

**Issue by LukasDoesDev** [tandpfun/skill-icons#82]
### Skill Name

SQLite

### Why?

SQLite is a very popular ([The most used, in fact](https://sqlite.org/mostdeployed.html)) library that implements a SQL database engine.

### Reference Image

![SQLite's image from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/3/38/SQLite370.svg)
source: https://en.wikipedia.org/wiki/File:SQLite370.svg

**Comment by tandpfun** [comment]
Added in 9904dfdfef9bf5d8ae649a85fcb531b5892b0796!
