### ISSUE TITLE
[NEW ICON] Vite

### ISSUE THREAD

**Issue by Amirovvv** [tandpfun/skill-icons#83]
### Skill Name

Vite

### Why?

Vite is a build tool for web development developed by Vue author Evan You, I think Vue developers might find it interesting.

### Reference Image

![68747470733a2f2f766974656a732e6465762f6c6f676f2e737667](https://user-images.githubusercontent.com/58747052/168891833-66d185d6-7f40-4594-9bd3-6749ffbc8047.svg)

**Comment by tandpfun** [comment]
Added in 9904dfdfef9bf5d8ae649a85fcb531b5892b0796!
