### ISSUE TITLE
[NEW ICON] FastAPI

### ISSUE THREAD

**Issue by skepfusky** [tandpfun/skill-icons#85]
### Skill Name

FastAPI

### Why?

Another Python web framework that's been gaining popularity and catching up between Flask and Django

### Reference Image

![logo-teal](https://user-images.githubusercontent.com/94678583/169478660-20733757-4f5e-41cc-9b42-568f6d4f2f53.png)

**Comment by tandpfun** [comment]
Added in 9904dfdfef9bf5d8ae649a85fcb531b5892b0796!
