### ISSUE TITLE
[NEW ICON] Pinia

### ISSUE THREAD

**Issue by Amirovvv** [tandpfun/skill-icons#86]
### Skill Name

Pinia

### Why?

The new official store library for Vue. I think Vue as a developer will be interested

### Reference Image

![68747470733a2f2f70696e69612e7675656a732e6f72672f6c6f676f2e737667](https://user-images.githubusercontent.com/58747052/169601548-0846601c-3d2f-47b0-9e22-d5ddb8589def.svg)

**Comment by tandpfun** [comment]
Not exactly a specific skill, I think vue would cover this
