### ISSUE TITLE
[NEW ICON] Flux Programming Language

### ISSUE THREAD

**Issue by DeveloperWOW64** [tandpfun/skill-icons#87]
### Skill Name

Flux

### Why?

It's a new programming language based on Python with aims to remove the gates of difficult language and understanding within coding while still keeping its functions of a broad variety.

### Reference Image

Sorry I can't give an SVG:
![95999427](https://user-images.githubusercontent.com/71598437/169640396-49bc7810-546d-4f5e-8141-e115f3927bab.png)

**Comment by tandpfun** [comment]
I appreciate the suggestion! Unfortunately the skill isn't widely used enough to be added.
