### ISSUE TITLE
[NEW ICON] [COMPLETED] Forth

### ISSUE THREAD

**Issue by ThatOneCalculator** [tandpfun/skill-icons#88]
### Skill Name

Forth

### Why?

Very popular low level language implementing high level constructs. Also now officially supported by GitHub. https://forth-standard.org/

### Completed icon

![Forth](https://user-images.githubusercontent.com/44733677/169912796-0a2e8172-7a16-4a45-8e2b-7869c86f208e.svg)

**Comment by tandpfun** [comment]
Added in f100fddcf1ce9893e3c38be204a0adcfccfd18aa
