### ISSUE TITLE
[NEW ICON] LeetCode

### ISSUE THREAD

**Issue by prasadsawant7** [tandpfun/skill-icons#888]
### Skill Name

LeetCode 

### Why?

LeetCode icon would be great to have in the "I am also active on" section, as of now I am only using devto icon in that section.
It will be helpful for other people to redirect to respective programmer's LeetCode account.

### Reference Image

![leetcode](https://github.com/tandpfun/skill-icons/assets/58025997/72341efe-067a-44d6-b92a-055daa26f7d7)

**Comment by ghost** [comment]
I agree, I'm very active on LeetCode so it would be great to see this!

**Comment by LelouchFR** [comment]
@prasadsawant7 , @qingy2019 working on it ;)

**Comment by LelouchFR** [comment]
Open a issue on https://github.com/lelouchfr/skill-icons

**Comment by ghost** [comment]
wait so it won't be added to this repository??

**Comment by LelouchFR** [comment]
> wait so it won't be added to this repository??

Lets say the maintainer isnt doing anything... so if you want to wait 10 years to get it here :/

**Comment by ghost** [comment]
Alright, I'll open an issue :)

**Comment by prasadsawant7** [comment]
> > wait so it won't be added to this repository??
> 
> Lets say the maintainer isnt doing anything... so if you want to wait 10 years to get it here :/

Bro you are really doing great work, I have started your repo and will use your icons
