### ISSUE TITLE
[NEW ICON] Sketchup

### ISSUE THREAD

**Issue by Yeikzy** [tandpfun/skill-icons#89]
### Skill Name

Sketchup

### Why?

Sketchup is a tool widely used in companies for modeling.

### Reference Image

![Sketchup](https://www.dea.fr/wp-content/uploads/2017/01/logo-sketchup.jpg)

**Comment by tandpfun** [comment]
Added in f100fddcf1ce9893e3c38be204a0adcfccfd18aa
