### ISSUE TITLE
[NEW ICON] Apache Maven

### ISSUE THREAD

**Issue by Gescof** [tandpfun/skill-icons#90]
### Skill Name

Apache Maven

### Why?

A tool that can be used for building and managing any Java-based project. It's very popular and commonly used in many projects.

### Reference Image

![maven](https://user-images.githubusercontent.com/33986330/170699950-23e2d620-d852-417c-92f9-55bac6bd4734.png)

**Comment by tandpfun** [comment]
Added in f100fddcf1ce9893e3c38be204a0adcfccfd18aa
