### ISSUE TITLE
[NEW ICON] Gradle

### ISSUE THREAD

**Issue by Gescof** [tandpfun/skill-icons#91]
### Skill Name

Gradle

### Why?

An open-source build automation tool that is designed to be flexible enough to build almost any type of software. Pretty popular to build projects.

### Reference Image

![gradle](https://user-images.githubusercontent.com/33986330/170700750-b6a8ab51-ec33-499f-91a2-6443e93e7803.png)

**Comment by ThatOneCalculator** [comment]
Isn't that the old Gradle logo?

**Comment by ThatOneCalculator** [comment]
Yea, according to their brand guidelines it's fine to just use the new elephant on its own so it should be fine

**Comment by mjovanc** [comment]
Gradle would be great to have! Very useful tool.

**Comment by tandpfun** [comment]
Added in f100fddcf1ce9893e3c38be204a0adcfccfd18aa
