### ISSUE TITLE
[NEW ICON] Gmail

### ISSUE THREAD

**Issue by CHR-onicles** [tandpfun/skill-icons#92]
### Skill Name

Gmail

### Why?

If there's #53, then you do agree there should be a Gmail icon

### Reference Image

![image](https://user-images.githubusercontent.com/44934037/170768206-89d85443-6bfd-4847-9699-168090dd40ca.png)

**Comment by Explosion-Scratch** [comment]
Lmao "What are your skills?" "Uhm... Gmail?"

**Comment by tandpfun** [comment]
This isn't a skill

**Comment by AstroAnasTariq** [comment]
> ### Why?
> For people who give their contact mail ids in the readme.

https://github.com/tandpfun/skill-icons/issues/134#issue-1299830154

**Comment by Aazainkhan** [comment]
> Lmao "What are your skills?" "Uhm... Gmail?"

Neither is Instagram but its there 🤷🏽‍♂️

**Comment by tandpfun** [comment]
✅ Added in de91fca307a83d75fc5b1f6ce24540454acead41!

**Comment by CHR-onicles** [comment]
@tandpfun Thanks!
