### ISSUE TITLE
[BUG REPORT] Misspelling of elixir

### ISSUE THREAD

**Issue by mogeko** [tandpfun/skill-icons#93]
### The bug

I found a misspelling of elixir

### Steps to reproduce

when I use `https://skillicons.dev/icons?i=elixr`, it should be `elixir`

`https://skillicons.dev/icons?i=elixir` => ![](https://skillicons.dev/icons?i=elixir)

`https://skillicons.dev/icons?i=elixr` => ![](https://skillicons.dev/icons?i=elixr)

### Any extra info

Here are some screenshots from the [elixir official website](https://elixir-lang.org):

<img width="333" alt="截屏2022-05-29 18 35 22" src="https://user-images.githubusercontent.com/26341224/170881024-2b9cfe14-22c7-4bc2-b49b-331a8bdf5a1c.png">

**Comment by skepfusky** [comment]
@mogeko The issue has been resolved, you may close this issue now :3
