### ISSUE TITLE
[NEW ICON] ROS, ROS2, SolidWork

### ISSUE THREAD

**Issue by pangineering** [tandpfun/skill-icons#94]
### Skill Name

ROS, ROS2, SolidWork

### Why?

SolidWork for 3D design and Drawing

ROS and ROS2 are the robot operating system for developing robot.

**Comment by tandpfun** [comment]
Added ROS in f100fddcf1ce9893e3c38be204a0adcfccfd18aa
Probably not going to add solidworks
