### ISSUE TITLE
[BUG REPORT] Missing SurrealDB icon 404

### ISSUE THREAD

**Issue by ASoldo** [tandpfun/skill-icons#954]
### The bug

SurrealDB icon is missing

### Steps to reproduce

Broken image on https://github.com/lelouchfr/skill-icons?tab=readme-ov-file

**Comment by ASoldo** [comment]
I had to use new url `https://go-skill-icons.vercel.app/api/ ` instead of what i had before `https://skillicons.dev/icons?i=`. Now its working!

**Comment by LelouchFR** [comment]
it's not the same project, please close this issue, it has nothing to do with this version, if you have any issue with the new version, open issues at https://github.com/lelouchfr/skill-icon

**Comment by ASoldo** [comment]
why did I even try to contribute here? links that you share don't work , you shared to me the other url that you now say "good luck and have fun with other repo"...
