### ISSUE TITLE
[NEW ICON] Windows Server

### ISSUE THREAD

**Issue by waydealphax** [tandpfun/skill-icons#96]
### Skill Name

Windows Server

### Why?

Mentioned in #50 
Windows Server is commonly used today, and is a skill that relates to servers.
People should be able to show that they have knowledge with Windows Server and/or formal training with Windows Server.

**Comment by Benricheson101** [comment]
it takes skill to tolerate using Window Server and not switching to Linux :^)

**Comment by tandpfun** [comment]
This one isn't really a skill, probably not going to add
