### ISSUE TITLE
[NEW ICON] Ant Design, HalfMoon UI, NPM, Yarn, Pnpm, Postman

### ISSUE THREAD

**Issue by canaryGrapher** [tandpfun/skill-icons#97]
### Skill Name

Ant Design, HalfMoon UI, NPM, Yarn, Pnpm, Postman

### Why?

Ant Design and Halfmoon UI are popular libraries/frameworks for react applications.
NPM, Yarn, and Pnpm are popular package managers for javascript projects
Postman is a popular API testing tool

### Reference Image

![download](https://user-images.githubusercontent.com/27415791/171732151-9710bb5a-bb70-464c-b451-8b907d359f7c.jpg)
![download](https://user-images.githubusercontent.com/27415791/171732219-b04f20ea-b32d-4a35-9af5-537ee824de45.png)
![download](https://user-images.githubusercontent.com/27415791/171732416-9283a492-db77-4b04-9d83-27e74e8f7b12.png)
![download](https://user-images.githubusercontent.com/27415791/171732442-08cc1664-cd7f-4426-995e-ad555323e5a8.png)
![download](https://user-images.githubusercontent.com/27415791/171732726-1d66c7c7-3a09-46f2-9b7c-239e8f23bb0c.png)
![download](https://user-images.githubusercontent.com/27415791/171732752-a89561db-09d7-43c4-8e28-ddf6a955d773.png)

**Comment by ThatOneCalculator** [comment]
These are all tools with very low learning curves, not quite skills (Ant design is literally just a templated framework)

**Comment by ThatOneCalculator** [comment]
None of these are skills
