### ISSUE TITLE
[NEW ICON] YAML

### ISSUE THREAD

**Issue by fernandogprieto** [tandpfun/skill-icons#970]
### Skill Name

YAML

### Why?

It is commonly used for configuration files and in applications where data are being stored or transmitted. 

### Reference Image

![YAML](https://avatars.githubusercontent.com/u/69535?s=200&v=4)

**Comment by islandboymv** [comment]
> ### Skill Name
> YAML
> 
> ### Why?
> It is commonly used for configuration files and in applications where data are being stored or transmitted.
> 
> ### Reference Image
> ![YAML](https://avatars.githubusercontent.com/u/69535?s=200&v=4)

Hi [fernandogprieto]](https://github.com/fernandogprieto/fernandogprieto) 👋,

Thanks a bunch for reaching out! We've noticed the hiccup with updates in the repository. But no worries, we've got you covered! 😊 As an alternative, we've moved the icons to a new repository where updates are happening smoothly. You can find all the latest icons right here: [Icons 🏝️](https://github.com/islandboymv/icons).

And guess what? Your requested icon, **YAML**, is already there! 🎉 You can find it nestled among the others, ready to shine. ✨

Feel free to swing by, take a look, and even contribute if you'd like! It's an open invitation to join the fun. 🚀

Oh, and one more thing – if you find the icons useful, we'd be over the moon if you could give the repository a star ⭐. It helps others discover our little corner of the internet and means the world to us!

Additionally, if you're in a position to support the continued development and maintenance of this project, we'd greatly appreciate your sponsorship 💖. Every contribution helps us keep the lights on and the icons flowing!

Catch you later! 👋

Warm regards,
[islandboymv](https://github.com/islandboymv)

**Comment by LelouchFR** [comment]
@islandboymv @fernandogprieto hey, uhm... he just stole the code... so maybe come around and just ask it [here](https://github.com/lelouchfr/skill-icons), he does not have the right to edit at any moment the license, so it's copyright infringement...

**Comment by islandboymv** [comment]
> @islandboymv @fernandogprieto hey, uhm... he just stole the code... so maybe come around and just ask it [here](https://github.com/lelouchfr/skill-icons), he does not have the right to edit at any moment the license, so it's copyright infringement... 

I just figured out what you were saying and I’m truly sorry. I have included the original License in the repo. Other than that i still am allowed to update modify or use any work under an MiT License. And also if you are still willing to accept pull request made to your repo i would like to make contributions to it too.

**Comment by fernandogprieto** [comment]
@LelouchFR Hello Thanks I'm confused Why do u have another repo?.... you can do a pull request with the new icons?

**Comment by LelouchFR** [comment]
Hi @fernandogprieto , I created a new repository to kinda "migrate" people because the maintainer did not show up for months soo... I made the repository to respond to the issues people ask. I have rewritten it in golang for better performance and an easier way for people to work with it. You can make an issue if you want, we have about 125+ icons more than here. And a little tldr [here](https://github.com/tandpfun/skill-icons/pull/834)

**Comment by fernandogprieto** [comment]
Hello @LelouchFR, thanks for your response bro u don't have yaml icon in your repository

**Comment by LelouchFR** [comment]
@fernandogprieto Going to implement that as soon as I get back home from school ;)

**Comment by LelouchFR** [comment]
@fernandogprieto done 👍 ;)

**Comment by fernandogprieto** [comment]
Thanks bro, but I don't see the letter because of the dark theme could you change the yam to white within dark theme or is it much work?

**Comment by LelouchFR** [comment]
> Thanks bro, but I don't see the letter because of the dark theme could you change the yam to white within dark theme or is it much work?

Sure, going to make that now, will not take not too much time, since I thought about it too, but just needed to see what other thinks

dont you think its kinda strange ?

![image](https://github.com/tandpfun/skill-icons/assets/75901978/1c99f304-f9e8-4b98-be5d-40b0c2a9c45e)

**Comment by fernandogprieto** [comment]
> > Thanks bro, but I don't see the letter because of the dark theme could you change the yam to white within dark theme or is it much work?
> 
> Sure, going to make that now, will not take not too much time, since I thought about it too, but just needed to see what other thinks
> 
> dont you think its kinda strange ?
> 
> ![image](https://private-user-images.githubusercontent.com/75901978/332874347-1c99f304-f9e8-4b98-be5d-40b0c2a9c45e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTQ2OTQsIm5iZiI6MTcxNjM5NDM5NCwicGF0aCI6Ii83NTkwMTk3OC8zMzI4NzQzNDctMWM5OWYzMDQtZjllOC00Yjk4LWJlNWQtNDBiMGMyYTljNDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDE2MTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ODRiYjY4ZjY5ZGU1Y2FiNzI1YWVmZjYyODcyOGJmM2VlYWE3NjI1MjBhYWNmNzE5NGNkMzY1YmFkODVmNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OOJC3y3rfdpHrmpqlluD_SSdK1uD7SYlHew7sxfH0f8)

it's worth it nice!

**Comment by LelouchFR** [comment]
@fernandogprieto done hehe, enjoy ;)
