### ISSUE TITLE
[NEW ICON] SFML

### ISSUE THREAD

**Issue by The-Phoenics** [tandpfun/skill-icons#971]
### Skill Name

SFML

### Why?

It's popular among game & computer graphics programmers

### Reference Image

![sfml-icon](https://github.com/tandpfun/skill-icons/assets/96228962/b0f26622-a17b-4306-aaf5-f49a1594d2db)

**Comment by islandboymv** [comment]
> ### Skill Name
> SFML
> 
> ### Why?
> It's popular among game & computer graphics programmers
> 
> ### Reference Image
> ![sfml-icon](https://private-user-images.githubusercontent.com/96228962/331111258-b0f26622-a17b-4306-aaf5-f49a1594d2db.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNDkzNTgsIm5iZiI6MTcxNjI0OTA1OCwicGF0aCI6Ii85NjIyODk2Mi8zMzExMTEyNTgtYjBmMjY2MjItYTE3Yi00MzA2LWFhZjUtZjQ5YTE1OTRkMmRiLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDIzNTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MGQxY2JmNTAzMjJlODFmMTkwZjIxOWJjNDJkNjEzMDY3NzUwMTBmMjk1M2UxZGZiMmQ3MDAyODMwNjJiZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.woY3q-oxJGBC-wZFjVBReOXqFk6akIT2sTWg3YEyBhg)

Hi [[User]](https://github.com/The-Phoenics/The-Phoenics) 👋,

Thanks a bunch for reaching out! We've noticed the hiccup with updates in the repository. But no worries, we've got you covered! 😊 As an alternative, we've moved the icons to a new repository where updates are happening smoothly. You can find all the latest icons right here: [Icons 🏝️](https://github.com/islandboymv/icons).

And guess what? Your requested icon, **SFML**, is already there! 🎉 You can find it nestled among the others, ready to shine. ✨

Feel free to swing by, take a look, and even contribute if you'd like! It's an open invitation to join the fun. 🚀

Oh, and one more thing – if you find the icons useful, we'd be over the moon if you could give the repository a star ⭐. It helps others discover our little corner of the internet and means the world to us!

Additionally, if you're in a position to support the continued development and maintenance of this project, we'd greatly appreciate your sponsorship 💖. Every contribution helps us keep the lights on and the icons flowing!

Catch you later! 👋

Warm regards,
[islandboymv](https://github.com/islandboymv)
