### ISSUE TITLE
[NEW ICON] X (Twitter's new name)

### ISSUE THREAD

**Issue by aadium** [tandpfun/skill-icons#976]
### Skill Name

X

### Why?

Twitter has now rebranded itself as X

### Reference Image

![image](https://github.com/tandpfun/skill-icons/assets/47914987/3967357c-ca8f-4193-b3cc-bd6329776324)

**Comment by LelouchFR** [comment]
hey, I think I'm going to work on it [here](https://github.com/lelouchfr/skill-icons)

**Comment by LelouchFR** [comment]
@aadium is it how it should look like ?

![image](https://github.com/tandpfun/skill-icons/assets/75901978/efbcb6a0-2116-4ccd-b410-e7c84fa7d089)

**Comment by aadium** [comment]
> @aadium is it how it should look like ?
> 
> ![image](https://github.com/tandpfun/skill-icons/assets/75901978/efbcb6a0-2116-4ccd-b410-e7c84fa7d089)
> 

Yes

**Comment by LelouchFR** [comment]
@aadium Now you can use it with this link (see code [here](https://github.com/lelouchfr/skill-icons)):

```md
![icon](https://go-skill-icons.vercel.app/api/icons?i=x)
```

> [!NOTE]
> notice you can use also twitter instead of x (for user friendliness for others that have twitter in their icons link)

**Comment by aadium** [comment]
Looks good
