### ISSUE TITLE
[NEW ICON] HELM

### ISSUE THREAD

**Issue by fernandogprieto** [tandpfun/skill-icons#977]
### Skill Name

Helm

### Why?

The Kubernetes Package Manager

### Reference Image

![Helm](https://avatars.githubusercontent.com/u/15859888?s=200&v=4)

**Comment by LelouchFR** [comment]
Hey @fernandogprieto going to work it as soon as possible ;) It looks like a good icon idea !

**Comment by josemateuss** [comment]
@LelouchFR I can do this icon, what do you think?

**Comment by LelouchFR** [comment]
> @LelouchFR I can do this icon, what do you think?

Yes sure, feel free to help :)

**Comment by josemateuss** [comment]
@fernandogprieto take a look on https://github.com/LelouchFR/skill-icons/pull/50, it's already there :)

**Comment by fernandogprieto** [comment]
Thank you! it's working I will close the ticket.
