### ISSUE TITLE
[NEW ICON] Vagrant

### ISSUE THREAD

**Issue by fernandogprieto** [tandpfun/skill-icons#988]
### Skill Name

Vangrant

### Why?

Vagrant enables the creation and configuration of lightweight, reproducible, and portable development environments.

### Reference Image

![Vagrant](https://www.vagrantup.com/_next/static/media/vagrant-community_on-light.65c2be51.svg) only the letter V

**Comment by josemateuss** [comment]
@fernandogprieto if you prefer, you can open the suggestion in this [repo](https://github.com/LelouchFR/skill-icons), which is a repo with a lot more support and activity than here. the maintainer did not show up in months.

**Comment by fernandogprieto** [comment]
@josemateuss thanks but @LelouchFR always merged this repository to him.
