### ISSUE TITLE
[NEW ICON] Laravel Ecosystem Icons

### ISSUE THREAD

**Issue by eng-gabrielscardoso** [tandpfun/skill-icons#996]
### Skill Name

Laravel Ecosystem Icons

### Why?

The application currently supports the Laravel icon, but the ecosystem has many more technologies to be added. This ecosystem includes: 

- Forge
- Vapor
- Breeze
- Cashier
- Dusk
- Echo
- Envoyer
- Herd
- Horizon
- Inertia
- Jetstream
- Nova
- Octane
- Pennant
- Pint
- Prompts
- Pulse
- Reverb
- Sail
- Sanctum
- Scout
- Socialite
- Spark
- Telescope
- Pail
- Spark

### Reference Image

![image](https://github.com/tandpfun/skill-icons/assets/67348001/fdc33991-0b76-497a-a4fe-70d35b5032b5)

**Comment by eng-gabrielscardoso** [comment]
Laravel Pint better icon image

![image](https://github.com/tandpfun/skill-icons/assets/67348001/dd3d8832-0469-4e01-87b3-41cda7422b67)

**Comment by eng-gabrielscardoso** [comment]
Pail icon

![image](https://github.com/tandpfun/skill-icons/assets/67348001/e2c56155-0fce-4620-a259-621b89e970d9)

**Comment by eng-gabrielscardoso** [comment]
Laravel Spark

![images.png](https://github.com/tandpfun/skill-icons/assets/67348001/87d1dc29-a191-440d-9e46-c7d2df498566)

**Comment by ItsJoshBrown** [comment]
Hey @eng-gabrielscardoso, I've submitted a PR on the newest version of the project to add these since the maintainer hasn't shown up in months, you can check the repo [here](https://github.com/lelouchfr/skill-icons), and the PR https://github.com/LelouchFR/skill-icons/pull/96
