### ISSUE TITLE
[NEW ICON] Supabase

### ISSUE THREAD

**Issue by moha-b** [tandpfun/skill-icons#998]
### Skill Name

Subabase

### Why?

Supabase is an open source Firebase alternative.
Start your project with a Postgres database, Authentication, instant APIs, Edge Functions, Realtime subscriptions, Storage, and Vector embeddings.

### Reference Image

![](https://assets-global.website-files.com/655b60964be1a1b36c746790/655b60964be1a1b36c746d41_646dfce3b9c4849f6e401bff_supabase-logo-icon_1.png)

![](https://cdn.thenewstack.io/media/2021/12/d9fd0fdd-screen-shot-2021-12-20-at-11.47.03-am.png)

**Comment by LelouchFR** [comment]
supabase icon is already in there.

> [!NOTE]
> You might want to go at the newest version of the project which is located [here](https://github.com/lelouchfr/skill-icons)

**Comment by moha-b** [comment]
Oh, I found it. Sorry, my mistake. I searched the issues, but I didn't find anything about it.
